// STAGE add_to_cart — add ONE unit of the MAIN product through the page's own add-to-cart
// control (so the real theme handler runs and any drawer opens), verify the add, and read
// whatever surface opened. Picks an in-stock option first when the CTA is gated ("Select
// Size"). Never touches header / menu product cards. On Shopify, /cart.js is the source of
// truth and /cart/add.js (with an available variant) is the fallback. Never checks out.
// Option pickers in the buy box only: skip color/sibling pickers that navigate to another product,
// skip anything already chosen, pick the first enabled in-stock option of each unchosen group.
// Whatever opened after the click: drawer, notification, or nothing (a redirect shows as a location change).
// Self-contained: carries its own helpers, runs in any tab, in any order.
// GENERATED by build.py from src/add_to_cart.js. Do not edit here; edit src/ and rebuild.
// Paste everything below this line into javascript_tool's `text` unchanged. It returns a JSON string.
await (async () => {
try {
const clean = (s) => (s || '').replace(/\s+/g, ' ').trim();
const txt = (el, n = 240) => clean(el && (el.innerText !== undefined ? el.innerText : el.textContent)).slice(0, n);
const scripty = (s) => /[{};]|function|window\.|=>|\bvar\b|\bconst\b/.test(s);
const esc = (v) => (window.CSS && CSS.escape ? CSS.escape(v) : String(v).replace(/([^\w-])/g, '\\$1'));
const cx = (names, attr = 'class') => names.split(',').map((n) => `[${attr}*="${n}" i]`).join(',');
const vis = (el) => {
  if (!el || el.nodeType !== 1) return false;
  const r = el.getBoundingClientRect();
  if (r.width < 2 || r.height < 2) return false;
  const cs = getComputedStyle(el);
  return cs.visibility !== 'hidden' && cs.display !== 'none' && cs.opacity !== '0';
};
const aboveFold = (el) => {
  if (!el) return false;
  const r = el.getBoundingClientRect();
  return r.top + window.scrollY < window.innerHeight && r.bottom > 0;
};
const q = (s, root = document) => { try { return root.querySelector(s); } catch (e) { return null; } };
const qa = (s, root = document) => { try { return [...root.querySelectorAll(s)]; } catch (e) { return []; } };
const goodClass = (c) => /^[a-zA-Z][\w-]{2,40}$/.test(c) && !/^(css|sc|jsx|_|is-|has-)-?/.test(c) && !/[a-f0-9]{6,}|\d{3,}/.test(c);
const goodId = (id) => typeof id === 'string' && id.length > 0 && !/\d{3,}|[a-f0-9]{8,}/.test(id);
const unique = (s) => { try { return document.querySelectorAll(s).length === 1; } catch (e) { return false; } };
const sel = (el) => {
  if (!el || el.nodeType !== 1) return null;
  const id0 = el.getAttribute('id');
  if (goodId(id0) && unique('#' + esc(id0))) return '#' + esc(id0);
  for (const a of ['data-testid', 'data-test', 'data-id', 'name', 'data-action', 'aria-label']) {
    const v = el.getAttribute(a);
    if (v && v.length < 60) {
      const s = `${el.tagName.toLowerCase()}[${a}="${v.replace(/"/g, '\\"')}"]`;
      if (unique(s)) return s;
    }
  }
  const parts = [];
  let cur = el;
  for (let depth = 0; cur && cur.nodeType === 1 && depth < 6; depth++) {
    const cid = cur.getAttribute('id');
    if (goodId(cid)) { parts.unshift('#' + esc(cid)); break; }
    let part = cur.tagName.toLowerCase();
    const cls = [...cur.classList].filter(goodClass).slice(0, 2);
    if (cls.length) part += '.' + cls.map(esc).join('.');
    const p = cur.parentElement;
    if (p && (!cls.length || !unique(parts.length ? part + ' > ' + parts.join(' > ') : part))) {
      const sib = [...p.children].filter((c) => c.tagName === cur.tagName);
      if (sib.length > 1) part += `:nth-of-type(${sib.indexOf(cur) + 1})`;
    }
    parts.unshift(part);
    if (unique(parts.join(' > '))) break;
    cur = p;
  }
  return parts.join(' > ');
};
const isColumn = (el) => {
  if (!el || el === document.body) return true;
  if (/group-block-content|product__info|product-info|product-details|shopify-section|cart__contents|cart-items|drawer__inner/.test(el.className || '')) return true;
  const cs = getComputedStyle(el);
  const kids = el.children.length;
  return (cs.display === 'grid' && kids >= 2) || (cs.display === 'flex' && /column/.test(cs.flexDirection) && kids >= 3);
};
const block = (el) => {
  if (!el) return null;
  let cur = el;
  for (let i = 0; i < 12 && cur.parentElement && cur.parentElement !== document.body; i++) {
    if (isColumn(cur.parentElement)) break;
    cur = cur.parentElement;
  }
  return { block: sel(cur), column: sel(cur.parentElement) };
};
const rec = (el) => (el ? { selector: sel(el), text: txt(el, 48), aboveFold: aboveFold(el), ...block(el) } : null);
const platform = () => {
  if (window.Shopify && window.Shopify.shop) return 'shopify';
  if (window.BCData) return 'bigcommerce';
  if (window.dw || qa('a[href*="/on/demandware.store/"]').length) return 'salesforce-commerce-cloud';
  if (document.body.classList.contains('woocommerce') || qa('.woocommerce').length) return 'woocommerce';
  if (qa('[data-mage-init], body.catalog-product-view, body.cms-index-index').length) return 'magento';
  return 'custom';
};
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const shopifyCart = async () => { try { const r = await fetch('/cart.js', { credentials: 'same-origin' }); return r.ok ? await r.json() : null; } catch (e) { return null; } };
const productForm = () => {
  const main = q('main') || document.body;
  const h1 = qa('h1', main).find(vis) || qa('h1').find(vis) || null;
  const bad = (el) => !!el.closest('header, nav, footer, [class*="menu" i], [id*="menu" i], [class*="mega" i], [class*="drawer" i]:not([class*="product-info" i]), [id*="drawer" i], [class*="recommend" i], [class*="upsell" i], [class*="card" i], product-card, dynamic-product-card, main-product[id*="card" i]');
  const forms = qa('form[action*="/cart/add"], form[data-product-form], product-form form, form[id*="product" i]').filter((f) => !bad(f) && (vis(f) || qa('button, input[type="submit"]', f).some(vis)));
  const after = (f) => !h1 || !!(h1.compareDocumentPosition(f) & Node.DOCUMENT_POSITION_FOLLOWING);
  const form = forms.find(after) || forms[0] || null;
  const info = (form && form.closest('main-product, product-info, .product__info-wrapper, .product__info-container, .product-single__meta, ' + cx('product-info,product__info,product-details,buy-box,product-form-wrapper'))) || (h1 && h1.closest('section, ' + cx('product'))) || (form && form.parentElement) || main;
  return { form, h1, info, candidates: forms.length };
};
// The open cart drawer, if any. Judged by VISIBLE descendants, not the host's own box: custom
// elements like <modal-dialog> are often display:inline with a 0x0 rect while their panel is laid out.
const cartDrawer = () => {
  const cands = qa('cart-drawer, modal-dialog, dialog, [role="dialog"], [aria-modal="true"], ' + cx('cart-drawer,cartdrawer,mini-cart,minicart,side-cart,slide-cart,ajax-cart,cart-notification') + ', ' + cx('cart-drawer,cartdrawer,mini-cart,minicart', 'id'));
  const panel = (el) => vis(el) && el.getBoundingClientRect().height > 150 ? el : qa('*', el).find((c) => vis(c) && c.getBoundingClientRect().height > 150 && c.getBoundingClientRect().width > 200) || null;
  return cands.find((el) => !/menu|search|newsletter|filter|country|geo/i.test(el.id + ' ' + el.className) && /cart|bag|basket|checkout/i.test(txt(el, 600)) && panel(el)) || null;
};
// Output layer. The browser tool cuts any result over 1,000 chars and blocks results that look like
// query strings (key=value&key=value) or base64. So: strip query strings, replace '&', shrink to
// MAX chars by trimming the longest arrays/strings, stash on window.__nw, and return chunk 1 of
// 900. The batch reads chunks 2-4 with: (window.__nw||'').slice(900,1800) etc.
const emit = (out, max = 3600) => {
  const clip = (v) => typeof v === 'string' ? v.replace(/\?(?=[\w-]+=)[^"\s]*/g, '').replace(/&/g, '+').replace(/[A-Za-z0-9+/]{60,}/g, (m) => m.slice(0, 50) + '…').slice(0, 200) : v;
  const walk = (v) => Array.isArray(v) ? v.map(walk) : v && typeof v === 'object' ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, walk(x)])) : clip(v);
  const o = walk(out);
  let s = JSON.stringify(o);
  for (let i = 0; i < 30 && s.length > max; i++) {
    const arrs = [];
    const scan = (v) => { if (Array.isArray(v)) { if (v.length > 1) arrs.push(v); v.forEach(scan); } else if (v && typeof v === 'object') Object.values(v).forEach(scan); };
    scan(o);
    if (!arrs.length) break;
    arrs.sort((a, b) => JSON.stringify(b).length - JSON.stringify(a).length)[0].pop();
    s = JSON.stringify(o);
  }
  if (s.length > max) s = s.slice(0, max - 12) + '…[capped]';
  window.__nw = s;
  const n = Math.ceil(s.length / 900);
  return (n > 1 ? '[chunk 1/' + n + '] ' : '') + s.slice(0, 900);
};

const out = { platform: platform(), method: null, added: false, itemCountBefore: null, itemCountAfter: null, variantSelected: [], ctaText: null, drawer: null, notes: [] };
const shop = out.platform === 'shopify';
const countBadge = () => { const b = qa(cx('cart-count,cart__count,cart-item-count,bubble') + ', [data-cart-count], ' + cx('cart-count', 'id')).find(vis); return b ? txt(b, 10) : null; };
if (shop) { const c = await shopifyCart(); out.itemCountBefore = c ? c.item_count : null; } else out.itemCountBefore = countBadge();
const { form, info, candidates } = productForm();
const findCta = () => (form && qa('button[type="submit"], input[type="submit"], button[name="add"]', form).find((el) => vis(el) && !/quick/i.test(el.id + ' ' + el.className))) || qa('button, input[type="submit"]', info).find((el) => vis(el) && /add to (cart|bag|basket)|select (a )?size/i.test(txt(el, 60) || el.value || ''));
let cta = findCta();
if (!form) out.notes.push('no visible main product form (' + candidates + ' candidates); CTA search limited to the buy-box region');
const gated = (el) => !el || el.disabled || el.getAttribute('aria-disabled') === 'true' || /select (a )?(size|colou?r|option)|choose/i.test(txt(el, 60) || el.value || '');
const optionRadios = () => qa('input[type="radio"]', info).filter((r) => { const f = r.closest('form[action*="/cart/add"], form[data-product-form]'); return (!f || f === form) && !r.closest('aside, header, footer, swiper-slide, product-card, dynamic-product-card, main-product[id*="card" i], ' + cx('filter,facet,sibling,card,recommend,slide,carousel,pairs')) && !/sibling|card|filter/i.test(r.name + ' ' + r.id) && (vis(r) || (r.labels && r.labels[0] && vis(r.labels[0]))); });
if (gated(cta) || optionRadios().some((r) => !optionRadios().some((x) => x.name === r.name && x.checked))) {
  const groups = {};
  for (const r of optionRadios()) (groups[r.name] = groups[r.name] || []).push(r);
  for (const [name, radios] of Object.entries(groups)) {
    if (radios.some((r) => r.checked)) continue;
    const soldOut = (r) => /sold|unavailable|disabled|out-of-stock|line-through/i.test(r.className + ' ' + (r.labels && r.labels[0] ? r.labels[0].className + ' ' + txt(r.labels[0], 40) : '') + ' ' + (r.parentElement ? r.parentElement.className : ''));
    const pick = radios.find((r) => !r.disabled && !soldOut(r)) || radios.find((r) => !r.disabled);
    if (pick) { try { pick.click(); out.variantSelected.push(name + ': ' + ((pick.value && pick.value !== 'on') ? pick.value : (pick.labels && pick.labels[0] ? txt(pick.labels[0], 20) : (pick.nextSibling && pick.nextSibling.textContent || '').trim().slice(0, 20)))); } catch (e) {} }
  }
  for (const s of qa('select', info).filter((s) => vis(s) && !/sort|country|currency|quantity/i.test(s.name + ' ' + s.id))) {
    if (s.selectedIndex <= 0 || s.options[s.selectedIndex].disabled) { const o = [...s.options].find((x) => !x.disabled && x.value && !/select|choose/i.test(x.textContent)); if (o) { s.value = o.value; s.dispatchEvent(new Event('change', { bubbles: true })); out.variantSelected.push((s.name || 'select') + ': ' + txt(o, 20)); } }
  }
  if (out.variantSelected.length) { await sleep(2000); cta = (form && qa('button[type="submit"], input[type="submit"], button[name="add"]', form).find((el) => vis(el) && !el.disabled && !/quick/i.test(el.id + ' ' + el.className))) || findCta(); }
}
if (!cta) out.notes.push('no add-to-cart control found');
else if (cta.disabled || cta.getAttribute('aria-disabled') === 'true') out.notes.push('add-to-cart control is disabled (' + (txt(cta, 40) || cta.value) + ')' + (out.variantSelected.length ? ' even after selecting ' + out.variantSelected.join(', ') : ''));
else { try { out.ctaText = txt(cta, 40) || cta.value; cta.click(); out.method = 'click'; } catch (e) { out.notes.push('click threw: ' + e.message); } }
await sleep(3500);
if (shop) {
  let c = await shopifyCart(); out.itemCountAfter = c ? c.item_count : null;
  if (c && c.item_count === out.itemCountBefore) {
    // Prefer an available variant from the product JSON; the form's id can point at a sold-out default.
    let vid = null;
    try { const pj = await (await fetch(location.pathname.replace(/\/$/, '') + '.js', { credentials: 'same-origin' })).json(); const cur = form && q('[name="id"]', form) && q('[name="id"]', form).value; const v = (pj.variants || []).find((x) => x.available && String(x.id) === String(cur)) || (pj.variants || []).find((x) => x.available); vid = v && v.id; if (v) out.notes.push('ajax variant: ' + (v.title || v.id)); } catch (e) {}
    if (!vid) vid = (form && q('[name="id"]', form) && q('[name="id"]', form).value) || null;
    if (vid) {
      try {
        const r = await fetch('/cart/add.js', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify({ items: [{ id: Number(vid), quantity: 1 }] }) });
        out.notes.push((out.method ? 'click did not change /cart.js; ' : '') + 'used /cart/add.js (' + r.status + ')'); out.method = 'ajax';
        await sleep(1200); c = await shopifyCart(); out.itemCountAfter = c ? c.item_count : null;
      } catch (e) { out.notes.push('/cart/add.js failed: ' + e.message); }
    } else out.notes.push('no variant id available for the ajax fallback');
  }
  out.added = out.itemCountAfter != null && out.itemCountBefore != null && out.itemCountAfter > out.itemCountBefore;
  if (c && c.items && c.items.length) out.cartNow = c.items.map((i) => i.product_title + ' / ' + i.variant_title + ' / ' + (i.final_line_price / 100).toFixed(2)).slice(0, 3);
} else {
  out.itemCountAfter = countBadge();
  out.added = out.itemCountAfter !== out.itemCountBefore || !!cartDrawer();
  out.notes.push('non-Shopify: added is inferred from the cart badge / drawer; verify on the cart page');
}
const drawer = cartDrawer();
if (drawer) {
  const checkout = qa('button, a, input[type="submit"]', drawer).find((el) => vis(el) && /check ?out/i.test(txt(el, 40) || el.value || ''));
  const shipMsg = qa('p, div, span', drawer).filter((el) => vis(el) && el.children.length < 3 && /ship|deliver/i.test(txt(el, 160)) && txt(el, 160).length < 160 && !scripty(txt(el, 160))).slice(0, 3).map((el) => txt(el, 160));
  out.drawer = { kind: /notification|added/i.test(drawer.className) ? 'notification' : 'drawer', selector: sel(drawer), text: txt(drawer, 400), checkoutCta: checkout ? txt(checkout, 40) : null, shippingMessages: [...new Set(shipMsg)], freeShippingProgress: qa(cx('progress,shipping-bar,free-shipping,threshold') + ', progress', drawer).some(vis) || /away from|left (until|to|for) free|until free|more to (get|unlock|qualify)|to qualify|you('ve| have) (secured|unlocked|earned)/i.test(txt(drawer, 800)) };
  if (checkout) out.drawer.checkoutSelector = rec(checkout);
} else out.drawer = { kind: location.pathname.includes('/cart') ? 'redirected-to-cart-page' : 'none' };
out.locationAfter = location.pathname;
return emit(out);
} catch (e) { return JSON.stringify({ scriptError: String(e && e.message || e), stage: 'add_to_cart' }); }
})()

