#!/usr/bin/env python3
"""Build the paste-ready walkthrough scripts.

Each file in src/ (except _common.js) becomes scripts/walkthrough/<name>.js, self-contained:
only the shared helpers that stage references (transitively), then the stage body, wrapped as

    await (async () => { try { ... } catch (e) { return JSON.stringify({scriptError}) } })()

which is exactly what Claude in Chrome's `javascript_tool` evaluates (top-level await,
last expression returned). Every script returns a JSON string and never throws, so a
`browser_batch` containing it never stops on a missing element. Output is minified with
terser (when installed: `npm install -g terser`) because the run pastes each script
as output tokens; a smaller file is a faster walkthrough. Without terser the readable
build is written instead. Every script carries its own helpers (about 9 KB more pasted
per run than a shared library would cost), so no script depends on another having run
first and a store's CSP cannot break the read.

Run from anywhere:  python scripts/walkthrough/build.py
"""
import json
import re
import shutil
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "src"
ORDER = [
    "dismiss_consent", "read_home", "read_pdp", "add_to_cart", "read_cart",
    "click_checkout", "read_checkout_entry", "clear_cart", "read_policy", "read_collection",
]
HELPER_RE = re.compile(r"^const (\w+) = ", re.M)



def split_helpers(common: str) -> dict[str, str]:
    """Map helper name -> its full `const name = ...;` statement (top-level only)."""
    starts = [(m.start(), m.group(1)) for m in HELPER_RE.finditer(common)]
    helpers = {}
    for i, (pos, name) in enumerate(starts):
        end = starts[i + 1][0] if i + 1 < len(starts) else len(common)
        helpers[name] = common[pos:end].rstrip() + "\n"
    return helpers


def needed(body: str, helpers: dict[str, str]) -> list[str]:
    want, queue = set(), [body]
    while queue:
        text = queue.pop()
        for name in helpers:
            if name not in want and re.search(rf"\b{name}\b", text):
                want.add(name)
                queue.append(helpers[name])
    return [n for n in helpers if n in want]  # keep definition order


def minify(code: str) -> str | None:
    if not shutil.which("terser"):
        return None
    r = subprocess.run(
        ["terser", "--module", "--compress", "passes=2", "--mangle", "--format", "ascii_only=false,wrap_func_args=false"],
        input=code, capture_output=True, text=True,
    )
    if r.returncode != 0:
        raise SystemExit(f"terser failed: {r.stderr}")
    return r.stdout.strip()


def build() -> list[tuple[Path, int]]:
    helpers = split_helpers((SRC / "_common.js").read_text())
    bodies = {n: "\n".join(l for l in (SRC / f"{n}.js").read_text().splitlines() if not l.startswith("//")) for n in ORDER}
    headers = {n: "\n".join(l for l in (SRC / f"{n}.js").read_text().splitlines() if l.startswith("//")) for n in ORDER}
    written = []

    def wrap(name, prelude, body):
        return (f"await (async () => {{\ntry {{\n{prelude}\n{body}\n}} catch (e) {{ "
                f"return JSON.stringify({{ scriptError: String(e && e.message || e), stage: '{name}' }}); }}\n}})()\n")

    for name in ORDER:
        body = bodies[name]
        names = needed(body, helpers)
        code = wrap(name, "".join(helpers[n] for n in names), body)
        mini = minify(code)
        text = (f"{headers[name]}\n// Self-contained: carries its own helpers, runs in any tab, in any order.\n"
                f"// GENERATED by build.py from src/{name}.js. Do not edit here; edit src/ and rebuild.\n"
                f"// Paste everything below this line into javascript_tool's `text` unchanged. It returns a JSON string.\n" + (mini or code))
        path = HERE / f"{name}.js"; path.write_text(text + "\n"); written.append((path, len(text)))
    return written


def minify_body(src: str) -> str:
    """Minify a function body (helper definitions + return) by wrapping it as a function."""
    out = minify(f"function __lib(){{\n{src}\n}}")
    if out is None:
        return src
    m = re.match(r"function __lib\(\)\{(.*)\}$", out, re.S)
    return m.group(1) if m else src


if __name__ == "__main__":
    for p, n in build():
        print(f"{p.name:24s} {n:6d} bytes")
