// STAGE clear_cart — remove what the walkthrough added and verify the cart is empty.
// Shopify: POST /cart/clear.js (deterministic, no button hunting), verified via /cart.js.
// Others: fetch a remove link (a click would navigate and kill this script) or click a
// remove button, then re-read the cart in place; `verify` says when a reload is needed.
// Self-contained: carries its own helpers, runs in any tab, in any order.
// GENERATED by build.py from src/clear_cart.js. Do not edit here; edit src/ and rebuild.
// Paste everything below this line into javascript_tool's `text` unchanged. It returns a JSON string.
await (async () => {
try {
const clean = (s) => (s || '').replace(/\s+/g, ' ').trim();
const txt = (el, n = 240) => clean(el && (el.innerText !== undefined ? el.innerText : el.textContent)).slice(0, n);
const cx = (names, attr = 'class') => names.split(',').map((n) => `[${attr}*="${n}" i]`).join(',');
const vis = (el) => {
  if (!el || el.nodeType !== 1) return false;
  const r = el.getBoundingClientRect();
  if (r.width < 2 || r.height < 2) return false;
  const cs = getComputedStyle(el);
  return cs.visibility !== 'hidden' && cs.display !== 'none' && cs.opacity !== '0';
};
const qa = (s, root = document) => { try { return [...root.querySelectorAll(s)]; } catch (e) { return []; } };
const byText = (re, sels = 'button, a, [role="button"], input[type="submit"]', root = document) =>
  qa(sels, root).filter((el) => vis(el) && re.test(txt(el, 80) || el.getAttribute('aria-label') || el.value || ''));
const platform = () => {
  if (window.Shopify && window.Shopify.shop) return 'shopify';
  if (window.BCData) return 'bigcommerce';
  if (window.dw || qa('a[href*="/on/demandware.store/"]').length) return 'salesforce-commerce-cloud';
  if (document.body.classList.contains('woocommerce') || qa('.woocommerce').length) return 'woocommerce';
  if (qa('[data-mage-init], body.catalog-product-view, body.cms-index-index').length) return 'magento';
  return 'custom';
};
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const shopifyCart = async () => { try { const r = await fetch('/cart.js', { credentials: 'same-origin' }); return r.ok ? await r.json() : null; } catch (e) { return null; } };
const cartDrawer = () => {
  const cands = qa('cart-drawer, modal-dialog, dialog, [role="dialog"], [aria-modal="true"], ' + cx('cart-drawer,cartdrawer,mini-cart,minicart,side-cart,slide-cart,ajax-cart,cart-notification') + ', ' + cx('cart-drawer,cartdrawer,mini-cart,minicart', 'id'));
  const panel = (el) => vis(el) && el.getBoundingClientRect().height > 150 ? el : qa('*', el).find((c) => vis(c) && c.getBoundingClientRect().height > 150 && c.getBoundingClientRect().width > 200) || null;
  return cands.find((el) => !/menu|search|newsletter|filter|country|geo/i.test(el.id + ' ' + el.className) && /cart|bag|basket|checkout/i.test(txt(el, 600)) && panel(el)) || null;
};
// Output layer. The browser tool cuts any result over 1,000 chars and blocks results that look like
// query strings (key=value&key=value) or base64. So: strip query strings, replace '&', shrink to
// MAX chars by trimming the longest arrays/strings, stash on window.__nw, and return chunk 1 of
// 900. The batch reads chunks 2-4 with: (window.__nw||'').slice(900,1800) etc.
const emit = (out, max = 3600) => {
  const clip = (v) => typeof v === 'string' ? v.replace(/\?(?=[\w-]+=)[^"\s]*/g, '').replace(/&/g, '+').replace(/[A-Za-z0-9+/]{60,}/g, (m) => m.slice(0, 50) + '…').slice(0, 200) : v;
  const walk = (v) => Array.isArray(v) ? v.map(walk) : v && typeof v === 'object' ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, walk(x)])) : clip(v);
  const o = walk(out);
  let s = JSON.stringify(o);
  for (let i = 0; i < 30 && s.length > max; i++) {
    const arrs = [];
    const scan = (v) => { if (Array.isArray(v)) { if (v.length > 1) arrs.push(v); v.forEach(scan); } else if (v && typeof v === 'object') Object.values(v).forEach(scan); };
    scan(o);
    if (!arrs.length) break;
    arrs.sort((a, b) => JSON.stringify(b).length - JSON.stringify(a).length)[0].pop();
    s = JSON.stringify(o);
  }
  if (s.length > max) s = s.slice(0, max - 12) + '…[capped]';
  window.__nw = s;
  const n = Math.ceil(s.length / 900);
  return (n > 1 ? '[chunk 1/' + n + '] ' : '') + s.slice(0, 900);
};

const out = { platform: platform(), method: null, cleared: false, itemCount: null, notes: [] };
if (out.platform === 'shopify') {
  try {
    const r = await fetch('/cart/clear.js', { method: 'POST', credentials: 'same-origin', headers: { Accept: 'application/json' } });
    out.method = '/cart/clear.js (' + r.status + ')';
    await sleep(800);
    const c = await shopifyCart(); out.itemCount = c ? c.item_count : null; out.cleared = out.itemCount === 0;
  } catch (e) { out.notes.push('/cart/clear.js failed: ' + e.message); }
}
if (!out.cleared) {
  const root = cartDrawer() || document;
  const rows = () => qa(cx('cart-item,line-item,cart__item') + ', tr[class*="cart" i], [data-cart-item], cart-item').filter(vis).length;
  for (let i = 0; i < 3; i++) {
    const rm = byText(/^(remove|delete|×|✕)$/i, 'a, button, [role="button"]', root)[0] || qa('a[href*="quantity=0"], a[href*="/cart/change"], button[name="remove"], a[aria-label*="remove" i], button[aria-label*="remove" i], a[title*="remove" i], ' + cx('remove') + ':not(input)', root).find(vis);
    if (!rm) break;
    const href = rm.tagName === 'A' && rm.getAttribute('href');
    if (href && /quantity=0|\/cart\/change|remove|delete/i.test(href)) {
      try { const r = await fetch(href, { credentials: 'same-origin', redirect: 'follow' }); out.method = 'fetched remove link (' + r.status + ')'; out.verify = 'reload the cart URL and run clear_cart once more to confirm (it only reads when nothing is left to remove)'; } catch (e) { out.notes.push('remove fetch failed: ' + e.message); }
      break;
    }
    try { rm.click(); out.method = (out.method ? out.method + '; ' : '') + 'clicked remove'; } catch (e) { out.notes.push('remove click threw: ' + e.message); break; }
    await sleep(2500);
    if (!rows()) break;
  }
  if (out.platform === 'shopify') { const c = await shopifyCart(); out.itemCount = c ? c.item_count : rows(); } else out.itemCount = rows();
  out.cleared = out.itemCount === 0 || /empty|nothing in your (cart|bag)/i.test(txt(document.body, 3000));
  if (!out.cleared) out.notes.push('cart may still hold the item; report it so the user can clear it');
}
return emit(out);
} catch (e) { return JSON.stringify({ scriptError: String(e && e.message || e), stage: 'clear_cart' }); }
})()

