// STAGE click_checkout — from the cart surface, click the checkout control once (checkout
// goals only, to observe the first step). Follow it with a 4-second wait and
// read_checkout_entry.
// Self-contained: carries its own helpers, runs in any tab, in any order.
// GENERATED by build.py from src/click_checkout.js. Do not edit here; edit src/ and rebuild.
// Paste everything below this line into javascript_tool's `text` unchanged. It returns a JSON string.
await (async () => {
try {
const clean = (s) => (s || '').replace(/\s+/g, ' ').trim();
const txt = (el, n = 240) => clean(el && (el.innerText !== undefined ? el.innerText : el.textContent)).slice(0, n);
const cx = (names, attr = 'class') => names.split(',').map((n) => `[${attr}*="${n}" i]`).join(',');
const vis = (el) => {
  if (!el || el.nodeType !== 1) return false;
  const r = el.getBoundingClientRect();
  if (r.width < 2 || r.height < 2) return false;
  const cs = getComputedStyle(el);
  return cs.visibility !== 'hidden' && cs.display !== 'none' && cs.opacity !== '0';
};
const q = (s, root = document) => { try { return root.querySelector(s); } catch (e) { return null; } };
const qa = (s, root = document) => { try { return [...root.querySelectorAll(s)]; } catch (e) { return []; } };
const cartDrawer = () => {
  const cands = qa('cart-drawer, modal-dialog, dialog, [role="dialog"], [aria-modal="true"], ' + cx('cart-drawer,cartdrawer,mini-cart,minicart,side-cart,slide-cart,ajax-cart,cart-notification') + ', ' + cx('cart-drawer,cartdrawer,mini-cart,minicart', 'id'));
  const panel = (el) => vis(el) && el.getBoundingClientRect().height > 150 ? el : qa('*', el).find((c) => vis(c) && c.getBoundingClientRect().height > 150 && c.getBoundingClientRect().width > 200) || null;
  return cands.find((el) => !/menu|search|newsletter|filter|country|geo/i.test(el.id + ' ' + el.className) && /cart|bag|basket|checkout/i.test(txt(el, 600)) && panel(el)) || null;
};
// Output layer. The browser tool cuts any result over 1,000 chars and blocks results that look like
// query strings (key=value&key=value) or base64. So: strip query strings, replace '&', shrink to
// MAX chars by trimming the longest arrays/strings, stash on window.__nw, and return chunk 1 of
// 900. The batch reads chunks 2-4 with: (window.__nw||'').slice(900,1800) etc.
const emit = (out, max = 3600) => {
  const clip = (v) => typeof v === 'string' ? v.replace(/\?(?=[\w-]+=)[^"\s]*/g, '').replace(/&/g, '+').replace(/[A-Za-z0-9+/]{60,}/g, (m) => m.slice(0, 50) + '…').slice(0, 200) : v;
  const walk = (v) => Array.isArray(v) ? v.map(walk) : v && typeof v === 'object' ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, walk(x)])) : clip(v);
  const o = walk(out);
  let s = JSON.stringify(o);
  for (let i = 0; i < 30 && s.length > max; i++) {
    const arrs = [];
    const scan = (v) => { if (Array.isArray(v)) { if (v.length > 1) arrs.push(v); v.forEach(scan); } else if (v && typeof v === 'object') Object.values(v).forEach(scan); };
    scan(o);
    if (!arrs.length) break;
    arrs.sort((a, b) => JSON.stringify(b).length - JSON.stringify(a).length)[0].pop();
    s = JSON.stringify(o);
  }
  if (s.length > max) s = s.slice(0, max - 12) + '…[capped]';
  window.__nw = s;
  const n = Math.ceil(s.length / 900);
  return (n > 1 ? '[chunk 1/' + n + '] ' : '') + s.slice(0, 900);
};

const root = cartDrawer() || q('main') || document.body;
const checkout = qa('button[name="checkout"], input[name="checkout"], a[href*="/checkout"]', root).find(vis) || qa('button, a, input[type="submit"]', root).find((el) => vis(el) && /check ?out|proceed/i.test(txt(el, 40) || el.value || ''));
if (!checkout) return emit({ clicked: false, note: 'no checkout control found' });
try { checkout.click(); } catch (e) { return emit({ clicked: false, note: 'click threw: ' + e.message }); }
return emit({ clicked: true, control: txt(checkout, 40) || checkout.value || null });
} catch (e) { return JSON.stringify({ scriptError: String(e && e.message || e), stage: 'click_checkout' }); }
})()

