// STAGE read_policy — read the shipping, returns, and FAQ/help pages WITHOUT navigating:
// fetches them from the current page (run it on the homepage, right after read_home) and
// returns, per page, the sentences that state thresholds, fees, delivery times, return
// windows, and conditions, verbatim. Tries Shopify's canonical policy URLs first, then
// footer links whose text mentions shipping, returns, FAQ, or help (same origin only).
// Returns chunk 1 of a JSON string; the batch reads chunks 2-4 from window.__nw.
// Self-contained: carries its own helpers, runs in any tab, in any order.
// GENERATED by build.py from src/read_policy.js. Do not edit here; edit src/ and rebuild.
// Paste everything below this line into javascript_tool's `text` unchanged. It returns a JSON string.
await (async () => {
try {
const clean = (s) => (s || '').replace(/\s+/g, ' ').trim();
const txt = (el, n = 240) => clean(el && (el.innerText !== undefined ? el.innerText : el.textContent)).slice(0, n);
const scripty = (s) => /[{};]|function|window\.|=>|\bvar\b|\bconst\b/.test(s);
const q = (s, root = document) => { try { return root.querySelector(s); } catch (e) { return null; } };
const qa = (s, root = document) => { try { return [...root.querySelectorAll(s)]; } catch (e) { return []; } };
const platform = () => {
  if (window.Shopify && window.Shopify.shop) return 'shopify';
  if (window.BCData) return 'bigcommerce';
  if (window.dw || qa('a[href*="/on/demandware.store/"]').length) return 'salesforce-commerce-cloud';
  if (document.body.classList.contains('woocommerce') || qa('.woocommerce').length) return 'woocommerce';
  if (qa('[data-mage-init], body.catalog-product-view, body.cms-index-index').length) return 'magento';
  return 'custom';
};
const emit = (out, max = 3600) => {
  const clip = (v) => typeof v === 'string' ? v.replace(/\?(?=[\w-]+=)[^"\s]*/g, '').replace(/&/g, '+').replace(/[A-Za-z0-9+/]{60,}/g, (m) => m.slice(0, 50) + '…').slice(0, 200) : v;
  const walk = (v) => Array.isArray(v) ? v.map(walk) : v && typeof v === 'object' ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, walk(x)])) : clip(v);
  const o = walk(out);
  let s = JSON.stringify(o);
  for (let i = 0; i < 30 && s.length > max; i++) {
    const arrs = [];
    const scan = (v) => { if (Array.isArray(v)) { if (v.length > 1) arrs.push(v); v.forEach(scan); } else if (v && typeof v === 'object') Object.values(v).forEach(scan); };
    scan(o);
    if (!arrs.length) break;
    arrs.sort((a, b) => JSON.stringify(b).length - JSON.stringify(a).length)[0].pop();
    s = JSON.stringify(o);
  }
  if (s.length > max) s = s.slice(0, max - 12) + '…[capped]';
  window.__nw = s;
  const n = Math.ceil(s.length / 900);
  return (n > 1 ? '[chunk 1/' + n + '] ' : '') + s.slice(0, 900);
};

const out = { pages: [], offSiteLinks: [], notes: [] };
const shop = platform() === 'shopify';
const urls = [];
const push = (u, why) => { try { const a = new URL(u, location.origin); if (a.origin !== location.origin) { const off = why + ' → ' + a.origin + a.pathname; if (/ship|deliver|return|refund|help|faq/i.test(why + a.href) && out.offSiteLinks.length < 4 && !out.offSiteLinks.includes(off)) out.offSiteLinks.push(off); return; } if (a.hash && a.pathname === location.pathname) return; if (!urls.some((x) => x.url === a.href)) urls.push({ url: a.origin + a.pathname, why }); } catch (e) {} };
if (shop) { push('/policies/shipping-policy', 'shopify canonical'); push('/policies/refund-policy', 'shopify canonical'); }
const footer = q('footer') || document.body;
for (const a of qa('a[href]', footer)) {
  const t = txt(a, 40) + ' ' + a.getAttribute('href');
  if (/privacy|terms|legal|accessib/i.test(t)) continue;
  if (/ship|deliver/i.test(t)) push(a.href, 'footer: ' + txt(a, 30));
  else if (/return|refund|exchange/i.test(t)) push(a.href, 'footer: ' + txt(a, 30));
  else if (/\bfaq|help|support/i.test(t) && !/contact/i.test(t)) push(a.href, 'footer: ' + txt(a, 30));
}
const keyRe = /free (standard |express |ground |u\.?s\.? )?(shipping|delivery)|orders? (over|above|of \$|totaling|\$)|[$€£]\s?\d|\d+\s?(business|working)? ?days?|within \d+|\d+-day|return|refund|exchange|restock|final sale|non-?returnable|flat rate|ship(s|ping) (to|within|from|time|cost)|deliver|carrier|tracking|threshold|minimum/i;
for (const { url, why } of urls.slice(0, 4)) {
  try {
    const r = await fetch(url, { credentials: 'same-origin', headers: { Accept: 'text/html' } });
    const doc = new DOMParser().parseFromString(await r.text(), 'text/html');
    for (const s of doc.querySelectorAll('script, style, noscript, nav, header, footer, svg, template')) s.remove();
    for (const el of doc.querySelectorAll('p, div, li, h1, h2, h3, h4, h5, h6, br, tr, td, th, section, article, dt, dd, summary, details')) el.insertAdjacentText('afterend', ' ');
    const h1 = doc.querySelector('h1');
    const title = clean(h1 ? h1.textContent : doc.title).slice(0, 60);
    // The policy body is the LARGEST of the known content containers (a class match alone can
    // hit a header strip whose class merely contains the word).
    let body = doc.body, best = 0;
    for (const s of ['.shopify-policy__body', '.shopify-policy__container', 'main', 'article', '[role="main"]', '.rte', '[class*="page-content" i]', '[class*="page__content" i]', '[class*="policy" i]']) for (const c of doc.querySelectorAll(s)) { const n = clean(c.textContent).length; if (n > best) { best = n; body = c; } }
    const raw = clean(body.textContent).replace(/[a-z0-9-]+\s*\{[^}]*\}/g, ' ').replace(/\s+/g, ' ');
    const notFound = !r.ok || /^(404|page not found|not found)/i.test(title) || /\b404\b|page (you requested )?(could not be found|does not exist)|page not found/i.test(raw.slice(0, 400)) || raw.length < 120;
    const sentences = raw.split(/(?<=[.!?])(?<!\b[A-Z]\.)(?<!\b(?:etc|vs|approx|incl|excl|no)\.)\s+(?=[A-Z0-9(])|\s{2,}/i).map((s) => s.trim()).filter((s) => s.length > 12 && s.length < 220);
    const seen = new Set(); const highlights = [];
    for (const s of sentences) if (keyRe.test(s) && !seen.has(s) && s.split(' ').length >= 4 && !scripty(s)) { seen.add(s); highlights.push(s); if (highlights.length >= 14) break; }
    out.pages.push({ url: url.replace(location.origin, ''), why, status: r.status, title, notFound, chars: raw.length, opening: raw.slice(0, 140), highlights });
  } catch (e) { out.pages.push({ url: url.replace(location.origin, ''), why, error: String(e && e.message || e) }); }
}
if (!out.pages.some((p) => !p.notFound && !p.error)) out.notes.push('no policy page readable by fetch; navigate to a footer link and use get_page_text');
return emit(out);
} catch (e) { return JSON.stringify({ scriptError: String(e && e.message || e), stage: 'read_policy' }); }
})()

