// STAGE read_collection — one read of a collection / category page: item count, default
// sort and options, filters, product cards (found generically: the grid cell around each
// product link, so custom card elements count too), quick add on cards (if it exists, any
// "add quick add" candidate dies), merchandising platform, and card selectors + containers.
// Returns chunk 1 of a JSON string; the batch reads chunks 2-4 from window.__nw.
// Sort control.
// Filters.
// Product cards: known card elements first, else the grid cell around each product link.
// Last resort (custom themes): the nearest card-sized ancestor of each product link, so a grid is never reported as 0 cards.
// Quick add on cards (hidden hover-only controls count as present).
// Merchandising / search platform hooks.
// Self-contained: carries its own helpers, runs in any tab, in any order.
// GENERATED by build.py from src/read_collection.js. Do not edit here; edit src/ and rebuild.
// Paste everything below this line into javascript_tool's `text` unchanged. It returns a JSON string.
await (async () => {
try {
const clean = (s) => (s || '').replace(/\s+/g, ' ').trim();
const txt = (el, n = 240) => clean(el && (el.innerText !== undefined ? el.innerText : el.textContent)).slice(0, n);
const esc = (v) => (window.CSS && CSS.escape ? CSS.escape(v) : String(v).replace(/([^\w-])/g, '\\$1'));
const cx = (names, attr = 'class') => names.split(',').map((n) => `[${attr}*="${n}" i]`).join(',');
const vis = (el) => {
  if (!el || el.nodeType !== 1) return false;
  const r = el.getBoundingClientRect();
  if (r.width < 2 || r.height < 2) return false;
  const cs = getComputedStyle(el);
  return cs.visibility !== 'hidden' && cs.display !== 'none' && cs.opacity !== '0';
};
const aboveFold = (el) => {
  if (!el) return false;
  const r = el.getBoundingClientRect();
  return r.top + window.scrollY < window.innerHeight && r.bottom > 0;
};
const q = (s, root = document) => { try { return root.querySelector(s); } catch (e) { return null; } };
const qa = (s, root = document) => { try { return [...root.querySelectorAll(s)]; } catch (e) { return []; } };
const byText = (re, sels = 'button, a, [role="button"], input[type="submit"]', root = document) =>
  qa(sels, root).filter((el) => vis(el) && re.test(txt(el, 80) || el.getAttribute('aria-label') || el.value || ''));
const goodClass = (c) => /^[a-zA-Z][\w-]{2,40}$/.test(c) && !/^(css|sc|jsx|_|is-|has-)-?/.test(c) && !/[a-f0-9]{6,}|\d{3,}/.test(c);
const goodId = (id) => typeof id === 'string' && id.length > 0 && !/\d{3,}|[a-f0-9]{8,}/.test(id);
const unique = (s) => { try { return document.querySelectorAll(s).length === 1; } catch (e) { return false; } };
const sel = (el) => {
  if (!el || el.nodeType !== 1) return null;
  const id0 = el.getAttribute('id');
  if (goodId(id0) && unique('#' + esc(id0))) return '#' + esc(id0);
  for (const a of ['data-testid', 'data-test', 'data-id', 'name', 'data-action', 'aria-label']) {
    const v = el.getAttribute(a);
    if (v && v.length < 60) {
      const s = `${el.tagName.toLowerCase()}[${a}="${v.replace(/"/g, '\\"')}"]`;
      if (unique(s)) return s;
    }
  }
  const parts = [];
  let cur = el;
  for (let depth = 0; cur && cur.nodeType === 1 && depth < 6; depth++) {
    const cid = cur.getAttribute('id');
    if (goodId(cid)) { parts.unshift('#' + esc(cid)); break; }
    let part = cur.tagName.toLowerCase();
    const cls = [...cur.classList].filter(goodClass).slice(0, 2);
    if (cls.length) part += '.' + cls.map(esc).join('.');
    const p = cur.parentElement;
    if (p && (!cls.length || !unique(parts.length ? part + ' > ' + parts.join(' > ') : part))) {
      const sib = [...p.children].filter((c) => c.tagName === cur.tagName);
      if (sib.length > 1) part += `:nth-of-type(${sib.indexOf(cur) + 1})`;
    }
    parts.unshift(part);
    if (unique(parts.join(' > '))) break;
    cur = p;
  }
  return parts.join(' > ');
};
const isColumn = (el) => {
  if (!el || el === document.body) return true;
  if (/group-block-content|product__info|product-info|product-details|shopify-section|cart__contents|cart-items|drawer__inner/.test(el.className || '')) return true;
  const cs = getComputedStyle(el);
  const kids = el.children.length;
  return (cs.display === 'grid' && kids >= 2) || (cs.display === 'flex' && /column/.test(cs.flexDirection) && kids >= 3);
};
const block = (el) => {
  if (!el) return null;
  let cur = el;
  for (let i = 0; i < 12 && cur.parentElement && cur.parentElement !== document.body; i++) {
    if (isColumn(cur.parentElement)) break;
    cur = cur.parentElement;
  }
  return { block: sel(cur), column: sel(cur.parentElement) };
};
const rec = (el) => (el ? { selector: sel(el), text: txt(el, 48), aboveFold: aboveFold(el), ...block(el) } : null);
const platform = () => {
  if (window.Shopify && window.Shopify.shop) return 'shopify';
  if (window.BCData) return 'bigcommerce';
  if (window.dw || qa('a[href*="/on/demandware.store/"]').length) return 'salesforce-commerce-cloud';
  if (document.body.classList.contains('woocommerce') || qa('.woocommerce').length) return 'woocommerce';
  if (qa('[data-mage-init], body.catalog-product-view, body.cms-index-index').length) return 'magento';
  return 'custom';
};
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const dismissOverlays = async () => {
  const out = { dismissed: [], left: [], declineSelector: null, closeSelector: null };
  const overlays = qa('[role="dialog"], [aria-modal="true"], ' + cx('consent,gdpr,popup,modal,newsletter,overlay') + ',' + cx('consent,onetrust,Cybot,popup', 'id'))
    .filter((el) => vis(el) && (/fixed|sticky/.test(getComputedStyle(el).position) || el.getAttribute('role') === 'dialog'));
  const declineRe = /^(decline( all)?|reject( all)?|refuse( all)?|deny( all)?|(only |strictly )?(necessary|essential)( only)?|no,? thanks?|not now|maybe later|continue without|i do not accept)$/i;
  const closeRe = /^(close|dismiss|×|✕|x)$/i;
  for (const o of overlays.slice(0, 6)) {
    const label = txt(o, 140);
    const decline = byText(declineRe, 'button, a, [role="button"]', o)[0];
    const close = byText(closeRe, 'button, a, [role="button"]', o)[0] || qa('button[aria-label*="close" i], a[aria-label*="close" i], [class*="close" i]', o).find(vis);
    const isConsent = /consent|privacy|tracking|we use|your experience/i.test(label) || /consent|onetrust|Cybot|gdpr/i.test(o.id + ' ' + o.className);
    if (decline) { out.declineSelector = out.declineSelector || sel(decline); try { decline.click(); } catch (e) {} out.dismissed.push({ kind: isConsent ? 'consent' : 'popup', via: 'decline', text: label }); continue; }
    if (close && (!isConsent || !byText(/accept|agree|allow|got it|ok/i, 'button, a, [role="button"]', o).length)) { out.closeSelector = out.closeSelector || sel(close); try { close.click(); } catch (e) {} out.dismissed.push({ kind: isConsent ? 'consent' : 'popup', via: 'close', text: label }); continue; }
    out.left.push({ kind: isConsent ? 'consent (no decline control; left unanswered)' : 'overlay', text: label, selector: sel(o) });
  }
  try { document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true })); } catch (e) {}
  if (out.dismissed.length) await sleep(500);
  return { dismissed: out.dismissed.map((d) => d.kind + ' via ' + d.via + ': ' + d.text.slice(0, 60)), left: out.left.map((l) => l.kind + ': ' + l.text.slice(0, 60) + ' [' + l.selector + ']'), declineSelector: out.declineSelector, closeSelector: out.closeSelector };
};

// The MAIN product form on a PDP: visible, inside main, after the visible h1, never a hidden
// header / mega-menu / drawer product card. Returns { form, h1, info } (info = the buy-box column).
const emit = (out, max = 3600) => {
  const clip = (v) => typeof v === 'string' ? v.replace(/\?(?=[\w-]+=)[^"\s]*/g, '').replace(/&/g, '+').replace(/[A-Za-z0-9+/]{60,}/g, (m) => m.slice(0, 50) + '…').slice(0, 200) : v;
  const walk = (v) => Array.isArray(v) ? v.map(walk) : v && typeof v === 'object' ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, walk(x)])) : clip(v);
  const o = walk(out);
  let s = JSON.stringify(o);
  for (let i = 0; i < 30 && s.length > max; i++) {
    const arrs = [];
    const scan = (v) => { if (Array.isArray(v)) { if (v.length > 1) arrs.push(v); v.forEach(scan); } else if (v && typeof v === 'object') Object.values(v).forEach(scan); };
    scan(o);
    if (!arrs.length) break;
    arrs.sort((a, b) => JSON.stringify(b).length - JSON.stringify(a).length)[0].pop();
    s = JSON.stringify(o);
  }
  if (s.length > max) s = s.slice(0, max - 12) + '…[capped]';
  window.__nw = s;
  const n = Math.ceil(s.length / 900);
  return (n > 1 ? '[chunk 1/' + n + '] ' : '') + s.slice(0, 900);
};

const out = { url: location.pathname, platform: platform(), title: null, productCountText: null, sort: null, filters: null, cards: { count: 0, aboveFold: 0, sample: [] }, quickAdd: null, merchandising: [], selectors: {}, notes: [], overlays: null };
out.overlays = await dismissOverlays();
const h1 = qa('h1').find(vis); out.title = h1 ? txt(h1, 60) : document.title.slice(0, 60);
const main = q('main') || document.body;
const cnt = qa('p, span, div, h2', main).filter((el) => vis(el) && /\b\d+\s+(products?|items?|results?|styles?)\b/i.test(txt(el, 60))).sort((a, b) => txt(a, 60).length - txt(b, 60).length)[0];
out.productCountText = cnt ? (txt(cnt, 60).match(/\d[\d,]*\s+(?:products?|items?|results?|styles?)/i) || [txt(cnt, 40)])[0] : null;
const sortSel = qa('select[name*="sort" i], select[id*="sort" i], select[class*="sort" i]', main).find(vis) || qa('select', main).find((s) => vis(s) && /best ?selling|price|newest|featured|alphabetically|relevance/i.test([...s.options].map((o) => o.text).join(' ')));
const sortBtn = qa('button, summary, a, label, span', main).find((el) => vis(el) && el.children.length < 4 && (/^sort( by)?:?/i.test(txt(el, 40)) || /sort/i.test(el.getAttribute('aria-label') || '')));
if (sortSel) out.sort = { control: 'select', current: sortSel.options[sortSel.selectedIndex] ? txt(sortSel.options[sortSel.selectedIndex], 30) : null, options: [...sortSel.options].map((o) => txt(o, 30)).slice(0, 8), selector: sel(sortSel) };
else if (sortBtn) out.sort = { control: 'button/menu', label: txt(sortBtn, 40), selector: sel(sortBtn), options: qa('[role="option"], [role="menuitem"], li, label, a, button', sortBtn.closest('details, div, form, ' + cx('sort')) || sortBtn.parentElement).map((o) => txt(o, 30)).filter((t, i, arr) => t.length > 2 && t.length < 30 && !/^sort/i.test(t) && arr.indexOf(t) === i).slice(0, 8) };
else out.sort = { control: 'none found' };
const filterRoot = qa('form[id*="filter" i], ' + cx('facet,filter') + ', aside, [id*="filter" i]', main).find((el) => (vis(el) || /dialog/i.test(el.tagName)) && qa('input, details, summary, button', el).length >= 2);
const filterBtn = byText(/^filters?( \(\d+\))?$/i, 'button, a, summary, label', main)[0];
out.filters = filterRoot ? { present: true, groups: [...new Set(qa('summary, legend, h3, h4, ' + cx('filter-title,facet-title,facet__label'), filterRoot).map((el) => txt(el, 24)).filter(Boolean))].slice(0, 10), layout: /aside/i.test(filterRoot.tagName) || (vis(filterRoot) && filterRoot.getBoundingClientRect().left < window.innerWidth / 3) ? 'sidebar' : 'drawer/top', selector: sel(filterRoot) } : filterBtn ? { present: true, layout: 'behind a button: ' + txt(filterBtn, 20), selector: sel(filterBtn) } : { present: false };
const links = qa('a[href*="/products/"], a[href*="/product/"], a[href*="/p/"]', main).filter((a) => !a.closest('header, nav, footer, ' + cx('breadcrumb,recommend,recently')));
const cellOf = (a) => { let el = a; for (let i = 0; i < 8 && el.parentElement && el.parentElement !== main; i++) { const p = el.parentElement; const cs = getComputedStyle(p); if (((cs.display === 'grid' || cs.display === 'flex' || /grid|collection|products|results|listing|swiper-wrapper/i.test(p.className)) && p.children.length >= 3)) return el; el = p; } return null; };
let cards = qa('product-card, dynamic-product-card, main-product[id*="card" i], ' + cx('product-card,card-product,product-item,product-grid-item,grid__item,product-tile,product-summary,product-block,productitem,product_card'), main).filter((c) => qa('a[href*="/product"], a[href*="/p/"]', c).length && !c.closest('header, nav, footer'));
if (cards.length < 3) cards = [...new Set(links.map(cellOf).filter(Boolean))];
if (cards.length < 3) cards = [...new Set(links.map((a) => { let el = a; for (let i = 0; i < 6 && el.parentElement && el.parentElement !== main; i++) { const r = el.getBoundingClientRect(); if (r.width > 120 && r.width < 700 && r.height > 150) return el; el = el.parentElement; } return null; }).filter(Boolean))];
cards = cards.filter((c) => !cards.some((o) => o !== c && o.contains(c)));
out.cards.count = cards.length;
out.cards.aboveFold = cards.filter((c) => vis(c) && aboveFold(c)).length;
out.cards.sample = cards.slice(0, 4).map((c) => { const a = q('a[href]', c); const p = qa('[class*="price" i]', c).find(vis); const link = qa('a[href*="/product"], a[href*="/p/"]', c).find((a) => txt(a, 40) && !/buy|off|sale|new/i.test(txt(a, 40))) ; const img = q('img[alt]', c); const title = (c.closest('[aria-label]') && (c.closest('[aria-label]').getAttribute('aria-label') || '').replace(/^product /i, '')) || (link && txt(link, 40)) || (img && img.alt.slice(0, 40)) || txt(q('h2, h3, [class*="title" i]', c), 40) || '?'; return title.slice(0, 40) + ' | ' + (p ? txt(p, 30) : 'no price') + (qa('[class*="badge" i], [class*="label" i]', c).find(vis) ? ' | badge: ' + txt(qa('[class*="badge" i], [class*="label" i]', c).find(vis), 30) : ''); });
if (cards[0]) { out.selectors.productCard = rec(cards[0]); const img = q('img', cards[0]); if (img) out.selectors.cardImage = rec(img); const pr = qa('[class*="price" i]', cards[0]).find(vis); if (pr) out.selectors.cardPrice = rec(pr); }
if (!cards.length) out.notes.push('no product cards recognized; run one find for "product card" in the fix-up batch to get its selector');
const qaBtn = cards.slice(0, 12).map((c) => qa('button, a, form[action*="/cart/add"] [type="submit"], ' + cx('quick,add-to-cart') + ', [data-quick-add], quick-shop-toggle button, quick-add-button', c).find((el) => /quick|add to (cart|bag)|^\+$|choose options|^add$/i.test(txt(el, 40) || el.getAttribute('aria-label') || '') || /quick-?(add|shop|view|buy)|add-to-cart/i.test(el.className + ' ' + el.id))).find(Boolean);
const sizeForms = cards.slice(0, 12).reduce((n, c) => n + qa('form[action*="/cart/add"]', c).length, 0);
out.quickAdd = qaBtn ? { present: true, text: txt(qaBtn, 30) || qaBtn.getAttribute('aria-label') || null, visibleWithoutHover: vis(qaBtn), addFormsInFirst12Cards: sizeForms, selector: sel(qaBtn) } : { present: false, addFormsInFirst12Cards: sizeForms, note: cards.length ? 'no quick-add control inside the first 12 cards' : 'no cards recognized, so unknown' };
if (qaBtn) out.selectors.quickAdd = rec(qaBtn);
const globals = { searchspring: !!window.SearchSpring || !!window.searchspring, nosto: !!window.Nosto || !!window.nostojs, klevu: !!window.klevu, algolia: !!window.algoliasearch || !!window.algoliaShopify, boost: !!window.boostPFSConfig || !!window.boostSDConfig || !!window.BoostPFS, searchanise: !!window.Searchanise, findify: !!window.findify, bloomreach: !!window.BrTrk, fastsimon: !!window.ISP_PROPERTIES || !!window.InstantSearchPlus, rebuy: !!window.Rebuy, visually: !!window.visually || !!q('[class*="vsly" i]') };
for (const [k, v] of Object.entries(globals)) if (v) out.merchandising.push(k);
for (const el of qa(cx('searchspring,nosto,klevu,ais-,boost-,snize,findify,ns-serp')).slice(0, 3)) out.merchandising.push((el.className.match(/searchspring|nosto|klevu|ais-|boost-|snize|findify|ns-serp/i) || [''])[0].toLowerCase());
out.merchandising = [...new Set(out.merchandising)];
out.gridTopPx = cards[0] && vis(cards[0]) ? Math.round(cards[0].getBoundingClientRect().top + window.scrollY) : null;
out.foldPx = window.innerHeight;
return emit(out);
} catch (e) { return JSON.stringify({ scriptError: String(e && e.message || e), stage: 'read_collection' }); }
})()

