// STAGE read_cart — one read of the cart surface with one item in it: the cart page, or the
// drawer when the store has no cart page (some redirect /cart to a drawer over the
// homepage). Items, shipping messaging verbatim, free-shipping progress, promo field,
// estimator, checkout CTA, express pay, upsells, extras, remove control, selectors.
// Returns chunk 1 of a JSON string; the batch reads chunks 2-4 from window.__nw.
// Shipping messaging, verbatim, inside the cart surface only.
// Free-shipping progress indicator.
// Promo / discount code field (visible, or behind a toggle).
// Shipping estimator.
// Checkout CTA.
// Express pay.
// Upsells / cross-sells.
// Extras worth knowing.
// Remove control (text first, then attributes; never a quantity input).
// Self-contained: carries its own helpers, runs in any tab, in any order.
// GENERATED by build.py from src/read_cart.js. Do not edit here; edit src/ and rebuild.
// Paste everything below this line into javascript_tool's `text` unchanged. It returns a JSON string.
await (async () => {
try {
const clean = (s) => (s || '').replace(/\s+/g, ' ').trim();
const txt = (el, n = 240) => clean(el && (el.innerText !== undefined ? el.innerText : el.textContent)).slice(0, n);
const scripty = (s) => /[{};]|function|window\.|=>|\bvar\b|\bconst\b/.test(s);
const esc = (v) => (window.CSS && CSS.escape ? CSS.escape(v) : String(v).replace(/([^\w-])/g, '\\$1'));
const cx = (names, attr = 'class') => names.split(',').map((n) => `[${attr}*="${n}" i]`).join(',');
const vis = (el) => {
  if (!el || el.nodeType !== 1) return false;
  const r = el.getBoundingClientRect();
  if (r.width < 2 || r.height < 2) return false;
  const cs = getComputedStyle(el);
  return cs.visibility !== 'hidden' && cs.display !== 'none' && cs.opacity !== '0';
};
const aboveFold = (el) => {
  if (!el) return false;
  const r = el.getBoundingClientRect();
  return r.top + window.scrollY < window.innerHeight && r.bottom > 0;
};
const q = (s, root = document) => { try { return root.querySelector(s); } catch (e) { return null; } };
const qa = (s, root = document) => { try { return [...root.querySelectorAll(s)]; } catch (e) { return []; } };
const byText = (re, sels = 'button, a, [role="button"], input[type="submit"]', root = document) =>
  qa(sels, root).filter((el) => vis(el) && re.test(txt(el, 80) || el.getAttribute('aria-label') || el.value || ''));
const goodClass = (c) => /^[a-zA-Z][\w-]{2,40}$/.test(c) && !/^(css|sc|jsx|_|is-|has-)-?/.test(c) && !/[a-f0-9]{6,}|\d{3,}/.test(c);
const goodId = (id) => typeof id === 'string' && id.length > 0 && !/\d{3,}|[a-f0-9]{8,}/.test(id);
const unique = (s) => { try { return document.querySelectorAll(s).length === 1; } catch (e) { return false; } };
const sel = (el) => {
  if (!el || el.nodeType !== 1) return null;
  const id0 = el.getAttribute('id');
  if (goodId(id0) && unique('#' + esc(id0))) return '#' + esc(id0);
  for (const a of ['data-testid', 'data-test', 'data-id', 'name', 'data-action', 'aria-label']) {
    const v = el.getAttribute(a);
    if (v && v.length < 60) {
      const s = `${el.tagName.toLowerCase()}[${a}="${v.replace(/"/g, '\\"')}"]`;
      if (unique(s)) return s;
    }
  }
  const parts = [];
  let cur = el;
  for (let depth = 0; cur && cur.nodeType === 1 && depth < 6; depth++) {
    const cid = cur.getAttribute('id');
    if (goodId(cid)) { parts.unshift('#' + esc(cid)); break; }
    let part = cur.tagName.toLowerCase();
    const cls = [...cur.classList].filter(goodClass).slice(0, 2);
    if (cls.length) part += '.' + cls.map(esc).join('.');
    const p = cur.parentElement;
    if (p && (!cls.length || !unique(parts.length ? part + ' > ' + parts.join(' > ') : part))) {
      const sib = [...p.children].filter((c) => c.tagName === cur.tagName);
      if (sib.length > 1) part += `:nth-of-type(${sib.indexOf(cur) + 1})`;
    }
    parts.unshift(part);
    if (unique(parts.join(' > '))) break;
    cur = p;
  }
  return parts.join(' > ');
};
const isColumn = (el) => {
  if (!el || el === document.body) return true;
  if (/group-block-content|product__info|product-info|product-details|shopify-section|cart__contents|cart-items|drawer__inner/.test(el.className || '')) return true;
  const cs = getComputedStyle(el);
  const kids = el.children.length;
  return (cs.display === 'grid' && kids >= 2) || (cs.display === 'flex' && /column/.test(cs.flexDirection) && kids >= 3);
};
const block = (el) => {
  if (!el) return null;
  let cur = el;
  for (let i = 0; i < 12 && cur.parentElement && cur.parentElement !== document.body; i++) {
    if (isColumn(cur.parentElement)) break;
    cur = cur.parentElement;
  }
  return { block: sel(cur), column: sel(cur.parentElement) };
};
const rec = (el) => (el ? { selector: sel(el), text: txt(el, 48), aboveFold: aboveFold(el), ...block(el) } : null);
const platform = () => {
  if (window.Shopify && window.Shopify.shop) return 'shopify';
  if (window.BCData) return 'bigcommerce';
  if (window.dw || qa('a[href*="/on/demandware.store/"]').length) return 'salesforce-commerce-cloud';
  if (document.body.classList.contains('woocommerce') || qa('.woocommerce').length) return 'woocommerce';
  if (qa('[data-mage-init], body.catalog-product-view, body.cms-index-index').length) return 'magento';
  return 'custom';
};
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const shopifyCart = async () => { try { const r = await fetch('/cart.js', { credentials: 'same-origin' }); return r.ok ? await r.json() : null; } catch (e) { return null; } };
const dismissOverlays = async () => {
  const out = { dismissed: [], left: [], declineSelector: null, closeSelector: null };
  const overlays = qa('[role="dialog"], [aria-modal="true"], ' + cx('consent,gdpr,popup,modal,newsletter,overlay') + ',' + cx('consent,onetrust,Cybot,popup', 'id'))
    .filter((el) => vis(el) && (/fixed|sticky/.test(getComputedStyle(el).position) || el.getAttribute('role') === 'dialog'));
  const declineRe = /^(decline( all)?|reject( all)?|refuse( all)?|deny( all)?|(only |strictly )?(necessary|essential)( only)?|no,? thanks?|not now|maybe later|continue without|i do not accept)$/i;
  const closeRe = /^(close|dismiss|×|✕|x)$/i;
  for (const o of overlays.slice(0, 6)) {
    const label = txt(o, 140);
    const decline = byText(declineRe, 'button, a, [role="button"]', o)[0];
    const close = byText(closeRe, 'button, a, [role="button"]', o)[0] || qa('button[aria-label*="close" i], a[aria-label*="close" i], [class*="close" i]', o).find(vis);
    const isConsent = /consent|privacy|tracking|we use|your experience/i.test(label) || /consent|onetrust|Cybot|gdpr/i.test(o.id + ' ' + o.className);
    if (decline) { out.declineSelector = out.declineSelector || sel(decline); try { decline.click(); } catch (e) {} out.dismissed.push({ kind: isConsent ? 'consent' : 'popup', via: 'decline', text: label }); continue; }
    if (close && (!isConsent || !byText(/accept|agree|allow|got it|ok/i, 'button, a, [role="button"]', o).length)) { out.closeSelector = out.closeSelector || sel(close); try { close.click(); } catch (e) {} out.dismissed.push({ kind: isConsent ? 'consent' : 'popup', via: 'close', text: label }); continue; }
    out.left.push({ kind: isConsent ? 'consent (no decline control; left unanswered)' : 'overlay', text: label, selector: sel(o) });
  }
  try { document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true })); } catch (e) {}
  if (out.dismissed.length) await sleep(500);
  return { dismissed: out.dismissed.map((d) => d.kind + ' via ' + d.via + ': ' + d.text.slice(0, 60)), left: out.left.map((l) => l.kind + ': ' + l.text.slice(0, 60) + ' [' + l.selector + ']'), declineSelector: out.declineSelector, closeSelector: out.closeSelector };
};

// The MAIN product form on a PDP: visible, inside main, after the visible h1, never a hidden
// header / mega-menu / drawer product card. Returns { form, h1, info } (info = the buy-box column).
const cartDrawer = () => {
  const cands = qa('cart-drawer, modal-dialog, dialog, [role="dialog"], [aria-modal="true"], ' + cx('cart-drawer,cartdrawer,mini-cart,minicart,side-cart,slide-cart,ajax-cart,cart-notification') + ', ' + cx('cart-drawer,cartdrawer,mini-cart,minicart', 'id'));
  const panel = (el) => vis(el) && el.getBoundingClientRect().height > 150 ? el : qa('*', el).find((c) => vis(c) && c.getBoundingClientRect().height > 150 && c.getBoundingClientRect().width > 200) || null;
  return cands.find((el) => !/menu|search|newsletter|filter|country|geo/i.test(el.id + ' ' + el.className) && /cart|bag|basket|checkout/i.test(txt(el, 600)) && panel(el)) || null;
};
// Output layer. The browser tool cuts any result over 1,000 chars and blocks results that look like
// query strings (key=value&key=value) or base64. So: strip query strings, replace '&', shrink to
// MAX chars by trimming the longest arrays/strings, stash on window.__nw, and return chunk 1 of
// 900. The batch reads chunks 2-4 with: (window.__nw||'').slice(900,1800) etc.
const emit = (out, max = 3600) => {
  const clip = (v) => typeof v === 'string' ? v.replace(/\?(?=[\w-]+=)[^"\s]*/g, '').replace(/&/g, '+').replace(/[A-Za-z0-9+/]{60,}/g, (m) => m.slice(0, 50) + '…').slice(0, 200) : v;
  const walk = (v) => Array.isArray(v) ? v.map(walk) : v && typeof v === 'object' ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, walk(x)])) : clip(v);
  const o = walk(out);
  let s = JSON.stringify(o);
  for (let i = 0; i < 30 && s.length > max; i++) {
    const arrs = [];
    const scan = (v) => { if (Array.isArray(v)) { if (v.length > 1) arrs.push(v); v.forEach(scan); } else if (v && typeof v === 'object') Object.values(v).forEach(scan); };
    scan(o);
    if (!arrs.length) break;
    arrs.sort((a, b) => JSON.stringify(b).length - JSON.stringify(a).length)[0].pop();
    s = JSON.stringify(o);
  }
  if (s.length > max) s = s.slice(0, max - 12) + '…[capped]';
  window.__nw = s;
  const n = Math.ceil(s.length / 900);
  return (n > 1 ? '[chunk 1/' + n + '] ' : '') + s.slice(0, 900);
};

const out = { url: location.pathname, platform: platform(), surface: null, itemCount: null, subtotal: null, itemsInCart: null, shippingMessages: [], freeShippingProgress: null, promoField: null, shippingEstimator: null, checkoutCta: null, expressPay: [], upsells: null, extras: [], removeControl: null, selectors: {}, notes: [], overlays: null };
out.overlays = await dismissOverlays();
const drawer = cartDrawer();
const onCartPage = /\/cart|\/basket|\/bag|checkout\/cart/i.test(location.pathname);
const root = drawer || (onCartPage ? (q('main') || q('[class*="cart" i]') || document.body) : null);
out.surface = drawer ? 'drawer' + (onCartPage ? ' (over the cart page)' : ' (site redirected /cart to a drawer over ' + location.pathname + ')') : onCartPage ? 'page' : 'unknown: not on a cart URL and no drawer open';
if (!root) { out.notes.push('no cart surface found; open the cart from its icon and re-run'); return emit(out); }
if (out.platform === 'shopify') { const c = await shopifyCart(); if (c) { out.itemCount = c.item_count; out.subtotal = (c.total_price / 100).toFixed(2) + ' ' + (c.currency || ''); out.itemsInCart = (c.items || []).map((i) => i.product_title + ' / ' + i.variant_title + ' / ' + (i.final_line_price / 100).toFixed(2)).slice(0, 3); } }
const rows = qa(cx('cart-item,line-item,cart__item') + ', tr[class*="cart" i], [data-cart-item], cart-item, [id*="CartItem" i]', root).filter(vis);
if (out.itemCount == null) { out.itemCount = rows.length; const sub = qa(cx('subtotal,total'), root).find((el) => vis(el) && /\d/.test(txt(el, 60))); out.subtotal = sub ? txt(sub, 60) : null; }
if (rows[0]) out.selectors.lineItem = rec(rows[0]);
const seen = new Set();
for (const el of qa('p, div, span, li, small, em, strong', root)) {
  if (!vis(el) || el.children.length > 3) continue;
  const t = txt(el, 160);
  if (t.length < 6 || t.length > 160 || seen.has(t) || scripty(t) || !/ship|deliver|dispatch|arrive/i.test(t)) continue;
  if ([...seen].some((s) => s.includes(t))) continue;
  seen.add(t); out.shippingMessages.push({ text: t, selector: sel(el) });
  if (out.shippingMessages.length >= 5) break;
}
if (!out.shippingMessages.length) out.shippingMessages = 'absent';
else out.selectors.cartShippingMessage = rec(q(out.shippingMessages[0].selector));
const prog = qa(cx('progress,shipping-bar,free-shipping,threshold,goal') + ', progress', root).find(vis);
const progText = qa('p, div, span', root).find((el) => vis(el) && el.children.length < 3 && /away from|left (until|to|for) free|until free (shipping|delivery)|more (to|for) (get|unlock|qualify|free)|to qualify for free|you('ve| have) (unlocked|earned|qualified|secured)|spend .* (more|to get)/i.test(txt(el, 160)));
out.freeShippingProgress = prog || progText ? { present: true, text: txt(progText || prog, 120), selector: sel(prog || progText) } : { present: false };
const promoInput = qa('input[name*="discount" i], input[name*="coupon" i], input[name*="promo" i], input[id*="discount" i], input[id*="coupon" i], input[placeholder*="code" i], input[placeholder*="discount" i], input[placeholder*="promo" i], input[placeholder*="coupon" i]', root).find(vis);
const promoToggle = qa('button, a, summary, label, span', root).find((el) => vis(el) && el.children.length < 3 && /(discount|promo|coupon|gift card|voucher) ?(code)?/i.test(txt(el, 60)) && txt(el, 60).length < 60);
out.promoField = promoInput ? { present: true, how: 'input visible', placeholder: promoInput.placeholder || null, selector: sel(promoInput) } : promoToggle ? { present: true, how: 'behind a toggle: ' + txt(promoToggle, 40), selector: sel(promoToggle) } : { present: false, note: out.platform === 'shopify' ? 'Shopify carts usually take codes at checkout, not in the cart' : null };
const est = qa(cx('shipping-calculator,shipping-estimat') + ', [data-shipping-estimator]', root).find(vis) || qa('button, a, summary, h2, h3, p', root).find((el) => vis(el) && /estimate shipping|shipping estimat|calculate shipping|get shipping rates/i.test(txt(el, 80)));
out.shippingEstimator = est ? { present: true, text: txt(est, 60), selector: sel(est) } : { present: false };
const checkout = qa('button[name="checkout"], input[name="checkout"], a[href*="/checkout"], button[form*="cart"][type="submit"]', root).find(vis) || qa('button, a, input[type="submit"]', root).find((el) => vis(el) && /check ?out|proceed|secure checkout/i.test(txt(el, 40) || el.value || ''));
if (checkout) { out.checkoutCta = { text: txt(checkout, 40) || checkout.value || null, disabled: !!checkout.disabled }; out.selectors.checkoutCta = rec(checkout); } else out.notes.push('no checkout control found on this surface');
for (const el of qa('shopify-payment-button, .shopify-payment-button, ' + cx('dynamic-checkout,additional-checkout,paypal,shop-pay,shopify-pay,apple-pay,google-pay,amazon-pay') + ', iframe[title*="PayPal" i], [data-shopify="dynamic-checkout-cart"]', root)) if (vis(el)) out.expressPay.push((txt(el, 30) || el.getAttribute('title') || el.tagName.toLowerCase()).toLowerCase());
out.expressPay = [...new Set(out.expressPay)];
const upHead = qa('h2, h3, h4, p', root).find((el) => vis(el) && /you may also like|you might also like|recommended|frequently bought|complete the look|pairs well|add-?ons|customers also|don'?t forget|before you go/i.test(txt(el, 80)));
const upBlock = qa(cx('upsell,cross-sell,crosssell,recommend,complementary'), root).find(vis);
out.upsells = upHead || upBlock ? { present: true, heading: upHead ? txt(upHead, 60) : null, products: qa('a[href*="/products/"], a[href*="/product"]', upBlock || upHead.parentElement).filter(vis).length, selector: sel(upBlock || upHead) } : { present: false };
for (const [k, re] of [['orderNote', /order note|special instructions|add a note/i], ['giftOption', /gift (wrap|message|option)/i], ['trustBadges', /secure checkout|ssl|money.?back|guarantee|safe (and|&) secure/i], ['continueShopping', /continue shopping/i], ['taxesShippingNote', /tax(es)? (and|&|,)? ?(discounts)?,? ?(and|&)? ?shipping (calculated|at checkout)|shipping (calculated|at checkout)/i], ['storePickup', /pick ?up in store|select store/i]]) {
  const el = qa('p, a, button, label, summary, span, div, small', root).find((x) => vis(x) && x.children.length < 3 && re.test(txt(x, 120)));
  if (el) out.extras.push(k + ': ' + txt(el, 80));
}
const rm = byText(/^(remove|delete|×|✕)$/i, 'a, button, [role="button"]', root)[0] || qa('a[href*="quantity=0"], a[href*="/cart/change"], button[name="remove"], a[aria-label*="remove" i], button[aria-label*="remove" i], a[title*="remove" i], cart-remove-button a, cart-remove-button button, ' + cx('remove') + ':not(input)', root).find(vis);
if (rm) { out.removeControl = { text: txt(rm, 20) || rm.getAttribute('aria-label') || null, selector: sel(rm) }; out.selectors.removeControl = rec(rm); }
return emit(out);
} catch (e) { return JSON.stringify({ scriptError: String(e && e.message || e), stage: 'read_cart' }); }
})()

