// STAGE read_checkout_entry — OBSERVATION ONLY of the first checkout step: guest vs
// account gate, express pay, how many fields, which steps. Enters nothing, clicks
// nothing. If the step shows nothing without data entry, say so and rely on the funnel.
// Self-contained: carries its own helpers, runs in any tab, in any order.
// GENERATED by build.py from src/read_checkout_entry.js. Do not edit here; edit src/ and rebuild.
// Paste everything below this line into javascript_tool's `text` unchanged. It returns a JSON string.
await (async () => {
try {
const clean = (s) => (s || '').replace(/\s+/g, ' ').trim();
const txt = (el, n = 240) => clean(el && (el.innerText !== undefined ? el.innerText : el.textContent)).slice(0, n);
const cx = (names, attr = 'class') => names.split(',').map((n) => `[${attr}*="${n}" i]`).join(',');
const vis = (el) => {
  if (!el || el.nodeType !== 1) return false;
  const r = el.getBoundingClientRect();
  if (r.width < 2 || r.height < 2) return false;
  const cs = getComputedStyle(el);
  return cs.visibility !== 'hidden' && cs.display !== 'none' && cs.opacity !== '0';
};
const aboveFold = (el) => {
  if (!el) return false;
  const r = el.getBoundingClientRect();
  return r.top + window.scrollY < window.innerHeight && r.bottom > 0;
};
const q = (s, root = document) => { try { return root.querySelector(s); } catch (e) { return null; } };
const qa = (s, root = document) => { try { return [...root.querySelectorAll(s)]; } catch (e) { return []; } };
const emit = (out, max = 3600) => {
  const clip = (v) => typeof v === 'string' ? v.replace(/\?(?=[\w-]+=)[^"\s]*/g, '').replace(/&/g, '+').replace(/[A-Za-z0-9+/]{60,}/g, (m) => m.slice(0, 50) + '…').slice(0, 200) : v;
  const walk = (v) => Array.isArray(v) ? v.map(walk) : v && typeof v === 'object' ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, walk(x)])) : clip(v);
  const o = walk(out);
  let s = JSON.stringify(o);
  for (let i = 0; i < 30 && s.length > max; i++) {
    const arrs = [];
    const scan = (v) => { if (Array.isArray(v)) { if (v.length > 1) arrs.push(v); v.forEach(scan); } else if (v && typeof v === 'object') Object.values(v).forEach(scan); };
    scan(o);
    if (!arrs.length) break;
    arrs.sort((a, b) => JSON.stringify(b).length - JSON.stringify(a).length)[0].pop();
    s = JSON.stringify(o);
  }
  if (s.length > max) s = s.slice(0, max - 12) + '…[capped]';
  window.__nw = s;
  const n = Math.ceil(s.length / 900);
  return (n > 1 ? '[chunk 1/' + n + '] ' : '') + s.slice(0, 900);
};

const out = { url: location.origin + location.pathname, reached: false, gate: null, expressPay: [], steps: [], fieldCount: null, fieldsAboveFold: null, fieldLabels: [], shippingOptionsVisible: [], notes: [] };
out.reached = /checkout|\/checkouts?\//i.test(location.href) || !!qa('h1, h2').find((el) => vis(el) && /checkout|contact|shipping|payment|information/i.test(txt(el, 40)));
if (!out.reached) { out.notes.push('this does not look like a checkout step (still on ' + location.pathname + ')'); return emit(out); }
const main = q('main') || document.body;
const lines = (main.innerText || '').split(/\n+/).map((l) => l.trim()).filter((l) => l.length > 2 && l.length < 200);
const gates = [];
for (const [k, re] of [['loginPrompt', /(log ?in|sign ?in)\b/i], ['guestOption', /continue as guest|guest checkout|checkout as guest/i], ['createAccount', /create (an )?account|sign ?up/i], ['emailFirst', /^(email|e-mail)/i]]) { const line = lines.find((l) => re.test(l)); if (line) gates.push(k + ': "' + line.slice(0, 80) + '"'); }
const pwd = qa('input[type="password"]').some(vis);
out.gate = { accountRequired: pwd && !gates.some((g) => /guestOption/.test(g)), signals: gates, passwordFieldVisible: pwd };
const payEls = qa('shopify-payment-button, ' + cx('dynamic-checkout,express,wallet,paypal,shop-pay,apple-pay,google-pay,amazon-pay') + ', iframe[title*="PayPal" i], button[aria-label*="pay" i]').filter(vis);
for (const el of payEls.filter((e) => !payEls.some((o) => o !== e && e.contains(o)))) out.expressPay.push((txt(el, 30) || el.getAttribute('title') || el.getAttribute('aria-label') || el.tagName.toLowerCase()).toLowerCase());
out.expressPay = [...new Set(out.expressPay)].slice(0, 6);
out.steps = [...new Set(qa('nav li, ' + cx('breadcrumb') + ' li, ' + cx('step') + ', h2', main).filter(vis).map((el) => txt(el, 30)).filter((t) => /cart|information|contact|shipping|delivery|payment|review|details/i.test(t)))].slice(0, 6);
const fields = qa('input:not([type="hidden"]):not([type="checkbox"]):not([type="radio"]):not([type="submit"]), select, textarea', main).filter(vis);
out.fieldCount = fields.length; out.fieldsAboveFold = fields.filter(aboveFold).length;
out.fieldLabels = [...new Set(fields.map((f) => f.getAttribute('placeholder') || f.getAttribute('aria-label') || f.name || f.id).filter(Boolean))].slice(0, 12);
for (const el of qa(cx('shipping-method,delivery') + ', [role="radiogroup"], fieldset', main)) if (vis(el) && /free|\$|€|£|\d+ days?/i.test(txt(el, 300))) out.shippingOptionsVisible.push(txt(el, 140));
out.shippingOptionsVisible = out.shippingOptionsVisible.slice(0, 3);
if (!fields.length && !gates.length) out.notes.push('step shows nothing without data entry; rely on funnel numbers');
return emit(out);
} catch (e) { return JSON.stringify({ scriptError: String(e && e.message || e), stage: 'read_checkout_entry' }); }
})()

