// STAGE read_home — one read of the homepage: platform + storefront (incl. market routing), third-party testing tools, announcement bar,
// hero, search, below-the-fold sections, policy links, cart URL, selectors, and a mid-priced
// in-stock product as the fallback for the cart path when the data names no product page.
// Returns chunk 1 of a JSON string; the batch reads chunks 2-4 from window.__nw.
// Market routing: a locale prefix on the path (/en-gb/, /fr-fr/) means the store serves several markets from one domain.
// Third-party experimentation tools on the page: globals they install, then the hosts their resources load from.
// Read from window and the resource timing list only (never from script tags or page source).
// Announcement bar: a visible strip near the top whose name says so.
// Hero: first big heading above the fold and its CTA.
// Search entry point.
// Sections below the fold, in order (compare with scroll-depth quantiles from the data).
// Policy / help links from the footer.
// Cart URL and icon.
// Fallback product for the cart path: mid-priced, in stock, from Shopify's /products.json (null elsewhere; the data's top product page is used first).
// Self-contained: carries its own helpers, runs in any tab, in any order.
// GENERATED by build.py from src/read_home.js. Do not edit here; edit src/ and rebuild.
// Paste everything below this line into javascript_tool's `text` unchanged. It returns a JSON string.
await (async () => {
try {
const clean = (s) => (s || '').replace(/\s+/g, ' ').trim();
const txt = (el, n = 240) => clean(el && (el.innerText !== undefined ? el.innerText : el.textContent)).slice(0, n);
const esc = (v) => (window.CSS && CSS.escape ? CSS.escape(v) : String(v).replace(/([^\w-])/g, '\\$1'));
const cx = (names, attr = 'class') => names.split(',').map((n) => `[${attr}*="${n}" i]`).join(',');
const vis = (el) => {
  if (!el || el.nodeType !== 1) return false;
  const r = el.getBoundingClientRect();
  if (r.width < 2 || r.height < 2) return false;
  const cs = getComputedStyle(el);
  return cs.visibility !== 'hidden' && cs.display !== 'none' && cs.opacity !== '0';
};
const aboveFold = (el) => {
  if (!el) return false;
  const r = el.getBoundingClientRect();
  return r.top + window.scrollY < window.innerHeight && r.bottom > 0;
};
const q = (s, root = document) => { try { return root.querySelector(s); } catch (e) { return null; } };
const qa = (s, root = document) => { try { return [...root.querySelectorAll(s)]; } catch (e) { return []; } };
const byText = (re, sels = 'button, a, [role="button"], input[type="submit"]', root = document) =>
  qa(sels, root).filter((el) => vis(el) && re.test(txt(el, 80) || el.getAttribute('aria-label') || el.value || ''));
const goodClass = (c) => /^[a-zA-Z][\w-]{2,40}$/.test(c) && !/^(css|sc|jsx|_|is-|has-)-?/.test(c) && !/[a-f0-9]{6,}|\d{3,}/.test(c);
const goodId = (id) => typeof id === 'string' && id.length > 0 && !/\d{3,}|[a-f0-9]{8,}/.test(id);
const unique = (s) => { try { return document.querySelectorAll(s).length === 1; } catch (e) { return false; } };
const sel = (el) => {
  if (!el || el.nodeType !== 1) return null;
  const id0 = el.getAttribute('id');
  if (goodId(id0) && unique('#' + esc(id0))) return '#' + esc(id0);
  for (const a of ['data-testid', 'data-test', 'data-id', 'name', 'data-action', 'aria-label']) {
    const v = el.getAttribute(a);
    if (v && v.length < 60) {
      const s = `${el.tagName.toLowerCase()}[${a}="${v.replace(/"/g, '\\"')}"]`;
      if (unique(s)) return s;
    }
  }
  const parts = [];
  let cur = el;
  for (let depth = 0; cur && cur.nodeType === 1 && depth < 6; depth++) {
    const cid = cur.getAttribute('id');
    if (goodId(cid)) { parts.unshift('#' + esc(cid)); break; }
    let part = cur.tagName.toLowerCase();
    const cls = [...cur.classList].filter(goodClass).slice(0, 2);
    if (cls.length) part += '.' + cls.map(esc).join('.');
    const p = cur.parentElement;
    if (p && (!cls.length || !unique(parts.length ? part + ' > ' + parts.join(' > ') : part))) {
      const sib = [...p.children].filter((c) => c.tagName === cur.tagName);
      if (sib.length > 1) part += `:nth-of-type(${sib.indexOf(cur) + 1})`;
    }
    parts.unshift(part);
    if (unique(parts.join(' > '))) break;
    cur = p;
  }
  return parts.join(' > ');
};
const isColumn = (el) => {
  if (!el || el === document.body) return true;
  if (/group-block-content|product__info|product-info|product-details|shopify-section|cart__contents|cart-items|drawer__inner/.test(el.className || '')) return true;
  const cs = getComputedStyle(el);
  const kids = el.children.length;
  return (cs.display === 'grid' && kids >= 2) || (cs.display === 'flex' && /column/.test(cs.flexDirection) && kids >= 3);
};
const block = (el) => {
  if (!el) return null;
  let cur = el;
  for (let i = 0; i < 12 && cur.parentElement && cur.parentElement !== document.body; i++) {
    if (isColumn(cur.parentElement)) break;
    cur = cur.parentElement;
  }
  return { block: sel(cur), column: sel(cur.parentElement) };
};
const rec = (el) => (el ? { selector: sel(el), text: txt(el, 48), aboveFold: aboveFold(el), ...block(el) } : null);
const platform = () => {
  if (window.Shopify && window.Shopify.shop) return 'shopify';
  if (window.BCData) return 'bigcommerce';
  if (window.dw || qa('a[href*="/on/demandware.store/"]').length) return 'salesforce-commerce-cloud';
  if (document.body.classList.contains('woocommerce') || qa('.woocommerce').length) return 'woocommerce';
  if (qa('[data-mage-init], body.catalog-product-view, body.cms-index-index').length) return 'magento';
  return 'custom';
};
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const priceText = (root = document) => {
  const m = txt(root, 20000).match(/(?:[$€£¥]|CA\$|US\$|A\$|C\$|USD|CAD|EUR|GBP|AUD)\s?\d[\d,.]*/);
  return m ? m[0] : null;
};
// Close the consent banner (decline only, never accept) and marketing popups. Returns what it did.
const dismissOverlays = async () => {
  const out = { dismissed: [], left: [], declineSelector: null, closeSelector: null };
  const overlays = qa('[role="dialog"], [aria-modal="true"], ' + cx('consent,gdpr,popup,modal,newsletter,overlay') + ',' + cx('consent,onetrust,Cybot,popup', 'id'))
    .filter((el) => vis(el) && (/fixed|sticky/.test(getComputedStyle(el).position) || el.getAttribute('role') === 'dialog'));
  const declineRe = /^(decline( all)?|reject( all)?|refuse( all)?|deny( all)?|(only |strictly )?(necessary|essential)( only)?|no,? thanks?|not now|maybe later|continue without|i do not accept)$/i;
  const closeRe = /^(close|dismiss|×|✕|x)$/i;
  for (const o of overlays.slice(0, 6)) {
    const label = txt(o, 140);
    const decline = byText(declineRe, 'button, a, [role="button"]', o)[0];
    const close = byText(closeRe, 'button, a, [role="button"]', o)[0] || qa('button[aria-label*="close" i], a[aria-label*="close" i], [class*="close" i]', o).find(vis);
    const isConsent = /consent|privacy|tracking|we use|your experience/i.test(label) || /consent|onetrust|Cybot|gdpr/i.test(o.id + ' ' + o.className);
    if (decline) { out.declineSelector = out.declineSelector || sel(decline); try { decline.click(); } catch (e) {} out.dismissed.push({ kind: isConsent ? 'consent' : 'popup', via: 'decline', text: label }); continue; }
    if (close && (!isConsent || !byText(/accept|agree|allow|got it|ok/i, 'button, a, [role="button"]', o).length)) { out.closeSelector = out.closeSelector || sel(close); try { close.click(); } catch (e) {} out.dismissed.push({ kind: isConsent ? 'consent' : 'popup', via: 'close', text: label }); continue; }
    out.left.push({ kind: isConsent ? 'consent (no decline control; left unanswered)' : 'overlay', text: label, selector: sel(o) });
  }
  try { document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true })); } catch (e) {}
  if (out.dismissed.length) await sleep(500);
  return { dismissed: out.dismissed.map((d) => d.kind + ' via ' + d.via + ': ' + d.text.slice(0, 60)), left: out.left.map((l) => l.kind + ': ' + l.text.slice(0, 60) + ' [' + l.selector + ']'), declineSelector: out.declineSelector, closeSelector: out.closeSelector };
};

// The MAIN product form on a PDP: visible, inside main, after the visible h1, never a hidden
// header / mega-menu / drawer product card. Returns { form, h1, info } (info = the buy-box column).
const emit = (out, max = 3600) => {
  const clip = (v) => typeof v === 'string' ? v.replace(/\?(?=[\w-]+=)[^"\s]*/g, '').replace(/&/g, '+').replace(/[A-Za-z0-9+/]{60,}/g, (m) => m.slice(0, 50) + '…').slice(0, 200) : v;
  const walk = (v) => Array.isArray(v) ? v.map(walk) : v && typeof v === 'object' ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, walk(x)])) : clip(v);
  const o = walk(out);
  let s = JSON.stringify(o);
  for (let i = 0; i < 30 && s.length > max; i++) {
    const arrs = [];
    const scan = (v) => { if (Array.isArray(v)) { if (v.length > 1) arrs.push(v); v.forEach(scan); } else if (v && typeof v === 'object') Object.values(v).forEach(scan); };
    scan(o);
    if (!arrs.length) break;
    arrs.sort((a, b) => JSON.stringify(b).length - JSON.stringify(a).length)[0].pop();
    s = JSON.stringify(o);
  }
  if (s.length > max) s = s.slice(0, max - 12) + '…[capped]';
  window.__nw = s;
  const n = Math.ceil(s.length / 900);
  return (n > 1 ? '[chunk 1/' + n + '] ' : '') + s.slice(0, 900);
};

const out = { url: location.href, platform: platform(), storefront: {}, testingTools: [], announcementBar: null, hero: {}, search: {}, pageHeightPx: document.documentElement.scrollHeight, foldPx: window.innerHeight, sectionsBelowFold: [], policyLinks: [], cartUrl: null, product: null, selectors: {}, overlays: null };
out.overlays = await dismissOverlays();
const path = (u) => { try { const a = new URL(u, location.origin); return a.origin === location.origin ? a.pathname : a.origin + a.pathname; } catch (e) { return null; } };
if (window.Shopify) out.storefront = { shop: Shopify.shop, country: Shopify.country || null, currency: (Shopify.currency && Shopify.currency.active) || null, locale: Shopify.locale || null, routeRoot: (Shopify.routes && Shopify.routes.root) || null };
out.storefront.firstPriceSeen = priceText();
out.storefront.htmlLang = document.documentElement.lang || null;
const pfx = location.pathname.match(/^\/([a-z]{2}(?:-[a-z]{2})?)(?=\/|$)/i);
out.storefront.pathPrefix = pfx ? '/' + pfx[1].toLowerCase() : null;
out.storefront.multiMarketHint = !!(out.storefront.pathPrefix || (out.storefront.routeRoot && out.storefront.routeRoot !== '/') || qa('a[hreflang]').length > 2);
const toolGlobals = [['Optimizely', 'optimizely'], ['VWO', '_vwo_code'], ['VWO', 'VWO'], ['Convert', 'convert'], ['AB Tasty', 'ABTasty'], ['Kameleoon', 'Kameleoon'], ['Dynamic Yield', 'DY'], ['Google Optimize', 'google_optimize'], ['Adobe Target', 'adobe'], ['Intelligems', 'igData'], ['Shoplift', 'Shoplift'], ['Visually', 'visually']];
const toolHosts = [['Optimizely', /optimizely\.com/i], ['VWO', /visualwebsiteoptimizer\.com|vwo\.com/i], ['Convert', /convertexperiments\.com/i], ['AB Tasty', /abtasty\.com/i], ['Kameleoon', /kameleoon\.(com|eu|io)/i], ['Dynamic Yield', /dynamicyield\.com/i], ['Adobe Target', /tt\.omtrdc\.net|adobedtm\.com/i], ['Intelligems', /intelligems\.io/i], ['Shoplift', /shoplift\.ai/i], ['Visually', /visually\.io/i], ['Omniconvert', /omniconvert\.com/i]];
const found = new Set();
for (const [name, g] of toolGlobals) { try { if (typeof window[g] !== 'undefined' && window[g] !== null) found.add(name); } catch (e) {} }
try { for (const r of performance.getEntriesByType('resource')) { for (const [name, re] of toolHosts) { if (re.test(r.name)) found.add(name); } } } catch (e) {}
out.testingTools = Array.from(found);
const bar = qa(cx('announcement,promo-bar,promobar,top-bar,topbar,marquee,ticker,usp,header__bar') + ',' + cx('announcement', 'id')).find((el) => vis(el) && el.getBoundingClientRect().top < 220 && txt(el, 400).length > 3);
if (bar) { out.announcementBar = txt(bar, 300); out.selectors.announcementBar = rec(bar); }
const main = q('main') || document.body;
const h = qa('h1, h2', main).find((el) => vis(el) && aboveFold(el));
if (h) {
  const region = h.closest('section, ' + cx('hero,banner,slide') + ', .shopify-section') || h.parentElement;
  const cta = qa('a, button', region).find((el) => vis(el) && txt(el, 60).length > 1 && txt(el, 60).length < 40);
  out.hero = { heading: txt(h, 100), cta: cta ? txt(cta, 40) : null, ctaHref: cta && cta.href ? path(cta.href) : null };
  if (cta) out.selectors.heroCta = rec(cta);
} else out.hero = { heading: null, note: 'no visible h1/h2 above the fold (hero may be image-only or still loading)' };
const sInput = qa('input[type="search"], input[name="q"], input[name="query"], input[placeholder*="search" i]').find(vis);
const sLink = qa('a[href*="/search"], button[aria-label*="search" i], [class*="search" i] button, summary[aria-label*="search" i]').find(vis) || byText(/^search$/i, 'button, a, summary, [role="button"]')[0];
out.search = { inputVisible: !!sInput, iconOrLink: !!sLink, placeholder: sInput ? sInput.placeholder : null };
if (sInput || sLink) out.selectors.search = rec(sInput || sLink);
out.sectionsBelowFold = qa('h2, h3', main).filter((el) => vis(el) && el.getBoundingClientRect().top + window.scrollY > window.innerHeight).slice(0, 12).map((el) => txt(el, 40) + ' @' + Math.round(el.getBoundingClientRect().top + window.scrollY));
const footer = q('footer') || document.body;
const seen = new Set();
for (const a of qa('a[href]', footer)) {
  const t = txt(a, 40); const p = path(a.href);
  if (!p || !/ship|deliver|return|refund|exchange|faq|help|policy/i.test(t + ' ' + p) || seen.has(p) || /^#|privacy|terms|legal/i.test(p + t)) continue;
  seen.add(p); out.policyLinks.push(t + ' → ' + p);
  if (out.policyLinks.length >= 8) break;
}
const cartLink = qa('a[href*="/cart"], a[href*="/basket"], a[href*="/bag"], a[aria-label*="cart" i], button[aria-label*="cart" i], ' + cx('cart', 'id') + ' a, [class*="cart" i] a').find(vis);
out.cartUrl = out.platform === 'shopify' ? '/cart' : (cartLink && cartLink.href ? path(cartLink.href) : null);
if (cartLink) out.selectors.cartIcon = rec(cartLink);
if (out.platform === 'shopify') {
  try {
    const r = await fetch('/products.json?limit=250', { credentials: 'same-origin' });
    const items = r.ok ? (await r.json()).products || [] : [];
    const cands = [];
    for (const p of items) {
      const v = (p.variants || []).find((x) => x.available);
      if (!v || !(parseFloat(v.price) > 0)) continue;
      cands.push({ title: p.title, handle: p.handle, variantId: v.id, variantTitle: v.title, price: parseFloat(v.price), type: p.product_type || null });
    }
    cands.sort((a, b) => a.price - b.price);
    if (cands.length) {
      const pick = cands[Math.floor(cands.length / 2)];
      out.product = { url: '/products/' + pick.handle, title: pick.title, price: pick.price, availableVariant: pick.variantId + ' (' + pick.variantTitle + ')', type: pick.type, pickedFrom: cands.length + ' in-stock products via /products.json, price range ' + cands[0].price + '-' + cands[cands.length - 1].price };
    } else out.product = { error: 'products.json returned no available products (' + items.length + ' products)' };
  } catch (e) { out.product = { error: 'products.json failed: ' + (e && e.message) }; }
}
return emit(out);
} catch (e) { return JSON.stringify({ scriptError: String(e && e.message || e), stage: 'read_home' }); }
})()

