// STAGE read_pdp — one read of a product page, scoped to the MAIN product (never a hidden
// header / mega-menu product card): what is above the fold, the CTA and its state,
// shipping/returns copy near the buy box (verbatim), third-party widgets, and the
// selectors + block containers a variation on this surface would touch.
// Returns chunk 1 of a JSON string; the batch reads chunks 2-4 from window.__nw.
// Price near the buy box.
// CTA: the add-to-cart control and its state.
// Option pickers in the buy box (up to 3: color, size, ...), each with its groups, option count and sold-out count.
// Shipping / returns / promo copy near the buy box, verbatim.
// Express pay on the PDP.
// Third-party widgets by known hooks.
// Above-the-fold checklist.
// Self-contained: carries its own helpers, runs in any tab, in any order.
// GENERATED by build.py from src/read_pdp.js. Do not edit here; edit src/ and rebuild.
// Paste everything below this line into javascript_tool's `text` unchanged. It returns a JSON string.
await (async () => {
try {
const clean = (s) => (s || '').replace(/\s+/g, ' ').trim();
const txt = (el, n = 240) => clean(el && (el.innerText !== undefined ? el.innerText : el.textContent)).slice(0, n);
const scripty = (s) => /[{};]|function|window\.|=>|\bvar\b|\bconst\b/.test(s);
const esc = (v) => (window.CSS && CSS.escape ? CSS.escape(v) : String(v).replace(/([^\w-])/g, '\\$1'));
const cx = (names, attr = 'class') => names.split(',').map((n) => `[${attr}*="${n}" i]`).join(',');
const vis = (el) => {
  if (!el || el.nodeType !== 1) return false;
  const r = el.getBoundingClientRect();
  if (r.width < 2 || r.height < 2) return false;
  const cs = getComputedStyle(el);
  return cs.visibility !== 'hidden' && cs.display !== 'none' && cs.opacity !== '0';
};
const aboveFold = (el) => {
  if (!el) return false;
  const r = el.getBoundingClientRect();
  return r.top + window.scrollY < window.innerHeight && r.bottom > 0;
};
const q = (s, root = document) => { try { return root.querySelector(s); } catch (e) { return null; } };
const qa = (s, root = document) => { try { return [...root.querySelectorAll(s)]; } catch (e) { return []; } };
const byText = (re, sels = 'button, a, [role="button"], input[type="submit"]', root = document) =>
  qa(sels, root).filter((el) => vis(el) && re.test(txt(el, 80) || el.getAttribute('aria-label') || el.value || ''));
const goodClass = (c) => /^[a-zA-Z][\w-]{2,40}$/.test(c) && !/^(css|sc|jsx|_|is-|has-)-?/.test(c) && !/[a-f0-9]{6,}|\d{3,}/.test(c);
const goodId = (id) => typeof id === 'string' && id.length > 0 && !/\d{3,}|[a-f0-9]{8,}/.test(id);
const unique = (s) => { try { return document.querySelectorAll(s).length === 1; } catch (e) { return false; } };
const sel = (el) => {
  if (!el || el.nodeType !== 1) return null;
  const id0 = el.getAttribute('id');
  if (goodId(id0) && unique('#' + esc(id0))) return '#' + esc(id0);
  for (const a of ['data-testid', 'data-test', 'data-id', 'name', 'data-action', 'aria-label']) {
    const v = el.getAttribute(a);
    if (v && v.length < 60) {
      const s = `${el.tagName.toLowerCase()}[${a}="${v.replace(/"/g, '\\"')}"]`;
      if (unique(s)) return s;
    }
  }
  const parts = [];
  let cur = el;
  for (let depth = 0; cur && cur.nodeType === 1 && depth < 6; depth++) {
    const cid = cur.getAttribute('id');
    if (goodId(cid)) { parts.unshift('#' + esc(cid)); break; }
    let part = cur.tagName.toLowerCase();
    const cls = [...cur.classList].filter(goodClass).slice(0, 2);
    if (cls.length) part += '.' + cls.map(esc).join('.');
    const p = cur.parentElement;
    if (p && (!cls.length || !unique(parts.length ? part + ' > ' + parts.join(' > ') : part))) {
      const sib = [...p.children].filter((c) => c.tagName === cur.tagName);
      if (sib.length > 1) part += `:nth-of-type(${sib.indexOf(cur) + 1})`;
    }
    parts.unshift(part);
    if (unique(parts.join(' > '))) break;
    cur = p;
  }
  return parts.join(' > ');
};
const isColumn = (el) => {
  if (!el || el === document.body) return true;
  if (/group-block-content|product__info|product-info|product-details|shopify-section|cart__contents|cart-items|drawer__inner/.test(el.className || '')) return true;
  const cs = getComputedStyle(el);
  const kids = el.children.length;
  return (cs.display === 'grid' && kids >= 2) || (cs.display === 'flex' && /column/.test(cs.flexDirection) && kids >= 3);
};
const block = (el) => {
  if (!el) return null;
  let cur = el;
  for (let i = 0; i < 12 && cur.parentElement && cur.parentElement !== document.body; i++) {
    if (isColumn(cur.parentElement)) break;
    cur = cur.parentElement;
  }
  return { block: sel(cur), column: sel(cur.parentElement) };
};
const rec = (el) => (el ? { selector: sel(el), text: txt(el, 48), aboveFold: aboveFold(el), ...block(el) } : null);
const platform = () => {
  if (window.Shopify && window.Shopify.shop) return 'shopify';
  if (window.BCData) return 'bigcommerce';
  if (window.dw || qa('a[href*="/on/demandware.store/"]').length) return 'salesforce-commerce-cloud';
  if (document.body.classList.contains('woocommerce') || qa('.woocommerce').length) return 'woocommerce';
  if (qa('[data-mage-init], body.catalog-product-view, body.cms-index-index').length) return 'magento';
  return 'custom';
};
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const priceText = (root = document) => {
  const m = txt(root, 20000).match(/(?:[$€£¥]|CA\$|US\$|A\$|C\$|USD|CAD|EUR|GBP|AUD)\s?\d[\d,.]*/);
  return m ? m[0] : null;
};
// Close the consent banner (decline only, never accept) and marketing popups. Returns what it did.
const dismissOverlays = async () => {
  const out = { dismissed: [], left: [], declineSelector: null, closeSelector: null };
  const overlays = qa('[role="dialog"], [aria-modal="true"], ' + cx('consent,gdpr,popup,modal,newsletter,overlay') + ',' + cx('consent,onetrust,Cybot,popup', 'id'))
    .filter((el) => vis(el) && (/fixed|sticky/.test(getComputedStyle(el).position) || el.getAttribute('role') === 'dialog'));
  const declineRe = /^(decline( all)?|reject( all)?|refuse( all)?|deny( all)?|(only |strictly )?(necessary|essential)( only)?|no,? thanks?|not now|maybe later|continue without|i do not accept)$/i;
  const closeRe = /^(close|dismiss|×|✕|x)$/i;
  for (const o of overlays.slice(0, 6)) {
    const label = txt(o, 140);
    const decline = byText(declineRe, 'button, a, [role="button"]', o)[0];
    const close = byText(closeRe, 'button, a, [role="button"]', o)[0] || qa('button[aria-label*="close" i], a[aria-label*="close" i], [class*="close" i]', o).find(vis);
    const isConsent = /consent|privacy|tracking|we use|your experience/i.test(label) || /consent|onetrust|Cybot|gdpr/i.test(o.id + ' ' + o.className);
    if (decline) { out.declineSelector = out.declineSelector || sel(decline); try { decline.click(); } catch (e) {} out.dismissed.push({ kind: isConsent ? 'consent' : 'popup', via: 'decline', text: label }); continue; }
    if (close && (!isConsent || !byText(/accept|agree|allow|got it|ok/i, 'button, a, [role="button"]', o).length)) { out.closeSelector = out.closeSelector || sel(close); try { close.click(); } catch (e) {} out.dismissed.push({ kind: isConsent ? 'consent' : 'popup', via: 'close', text: label }); continue; }
    out.left.push({ kind: isConsent ? 'consent (no decline control; left unanswered)' : 'overlay', text: label, selector: sel(o) });
  }
  try { document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true })); } catch (e) {}
  if (out.dismissed.length) await sleep(500);
  return { dismissed: out.dismissed.map((d) => d.kind + ' via ' + d.via + ': ' + d.text.slice(0, 60)), left: out.left.map((l) => l.kind + ': ' + l.text.slice(0, 60) + ' [' + l.selector + ']'), declineSelector: out.declineSelector, closeSelector: out.closeSelector };
};

// The MAIN product form on a PDP: visible, inside main, after the visible h1, never a hidden
// header / mega-menu / drawer product card. Returns { form, h1, info } (info = the buy-box column).
const productForm = () => {
  const main = q('main') || document.body;
  const h1 = qa('h1', main).find(vis) || qa('h1').find(vis) || null;
  const bad = (el) => !!el.closest('header, nav, footer, [class*="menu" i], [id*="menu" i], [class*="mega" i], [class*="drawer" i]:not([class*="product-info" i]), [id*="drawer" i], [class*="recommend" i], [class*="upsell" i], [class*="card" i], product-card, dynamic-product-card, main-product[id*="card" i]');
  const forms = qa('form[action*="/cart/add"], form[data-product-form], product-form form, form[id*="product" i]').filter((f) => !bad(f) && (vis(f) || qa('button, input[type="submit"]', f).some(vis)));
  const after = (f) => !h1 || !!(h1.compareDocumentPosition(f) & Node.DOCUMENT_POSITION_FOLLOWING);
  const form = forms.find(after) || forms[0] || null;
  const info = (form && form.closest('main-product, product-info, .product__info-wrapper, .product__info-container, .product-single__meta, ' + cx('product-info,product__info,product-details,buy-box,product-form-wrapper'))) || (h1 && h1.closest('section, ' + cx('product'))) || (form && form.parentElement) || main;
  return { form, h1, info, candidates: forms.length };
};
// The open cart drawer, if any. Judged by VISIBLE descendants, not the host's own box: custom
// elements like <modal-dialog> are often display:inline with a 0x0 rect while their panel is laid out.
const emit = (out, max = 3600) => {
  const clip = (v) => typeof v === 'string' ? v.replace(/\?(?=[\w-]+=)[^"\s]*/g, '').replace(/&/g, '+').replace(/[A-Za-z0-9+/]{60,}/g, (m) => m.slice(0, 50) + '…').slice(0, 200) : v;
  const walk = (v) => Array.isArray(v) ? v.map(walk) : v && typeof v === 'object' ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, walk(x)])) : clip(v);
  const o = walk(out);
  let s = JSON.stringify(o);
  for (let i = 0; i < 30 && s.length > max; i++) {
    const arrs = [];
    const scan = (v) => { if (Array.isArray(v)) { if (v.length > 1) arrs.push(v); v.forEach(scan); } else if (v && typeof v === 'object') Object.values(v).forEach(scan); };
    scan(o);
    if (!arrs.length) break;
    arrs.sort((a, b) => JSON.stringify(b).length - JSON.stringify(a).length)[0].pop();
    s = JSON.stringify(o);
  }
  if (s.length > max) s = s.slice(0, max - 12) + '…[capped]';
  window.__nw = s;
  const n = Math.ceil(s.length / 900);
  return (n > 1 ? '[chunk 1/' + n + '] ' : '') + s.slice(0, 900);
};

const out = { url: location.pathname, platform: platform(), title: null, price: null, inStock: null, aboveFold: {}, cta: null, variantSelector: null, shippingReturnsCopy: [], expressPayOnPdp: [], widgets: [], selectors: {}, selectedVariantId: null, notes: [], overlays: null };
out.overlays = await dismissOverlays();
const { form, h1, info, candidates } = productForm();
const titleEl = h1 || qa('h1, h2, [class*="product-title" i], [class*="product__title" i]', info).find((el) => vis(el) && txt(el, 100).length > 2) || qa('h1, h2', document.body).find((el) => vis(el) && !el.closest('header, nav, footer') && txt(el, 100).length > 2);
out.title = titleEl ? txt(titleEl, 100) : null;
if (!form) out.notes.push('no visible main product form found (' + candidates + ' candidates)');
const priceEl = qa('[class*="price" i], [data-price], [itemprop="price"]', info).find((el) => vis(el) && /\d/.test(txt(el, 40)) && txt(el, 40).length < 40) || qa('[class*="price" i], [data-price], [itemprop="price"]', document.body).find((el) => vis(el) && !el.closest('header, nav, footer, ' + cx('recommend,related,upsell,card')) && /^[^\d]{0,4}\d/.test(txt(el, 40)) && txt(el, 40).length < 40);
out.price = priceEl ? txt(priceEl, 60) : priceText(info);
if (priceEl) out.selectors.price = rec(priceEl);
const cta = (form && qa('button[type="submit"], input[type="submit"], button[name="add"]', form).find((el) => vis(el))) || (form && q('button[type="submit"], input[type="submit"], button[name="add"]', form)) || qa('button, a, input[type="submit"]', info).find((el) => vis(el) && /add to (cart|bag|basket)|buy now|select (a )?size|sold out|notify|pre-?order|out of stock/i.test(txt(el, 60) || el.value || ''));
if (cta) {
  const label = txt(cta, 60) || cta.value || cta.getAttribute('aria-label') || '';
  const disabled = !!(cta.disabled || cta.getAttribute('aria-disabled') === 'true' || /disabled/i.test(cta.className));
  out.cta = { text: label, disabled, visible: vis(cta), aboveFold: aboveFold(cta) };
  out.inStock = /sold out|out of stock|unavailable|notify/i.test(label) ? false : (disabled && /select|choose/i.test(label)) ? 'gated until an option is chosen ("' + label + '")' : !disabled;
  out.selectors.addToCart = rec(cta);
  if (form) out.selectors.productForm = rec(form);
} else out.notes.push('no add-to-cart control found in the main product region');
const idInput = form && q('[name="id"]', form); out.selectedVariantId = idInput ? idInput.value : null;
const hosts = [...new Set(qa('variant-selects, variant-radios, variant-picker, product-variant-picker, ' + cx('variant-picker,variant-selects,variant-radios,product-options,swatch,size-select'), info).filter(vis).map((el) => el.closest('variant-selects, variant-radios, variant-picker, product-variant-picker, ' + cx('variant,product-options')) || el))];
if (!hosts.length) { const f = qa('fieldset, select', info).find((el) => vis(el) && !/sort|country|currency|quantity/i.test(el.name + ' ' + el.id + ' ' + el.className)); if (f) hosts.push(f); }
const vhost = hosts[0] || null;
out.variantSelector = hosts.slice(0, 3).map((host) => {
  const opts = qa('option, input[type="radio"]', host);
  const legend = [...new Set(qa('legend, label.form__label, .form__label, ' + cx('option-name,option__label,option-label,label'), host).map((el) => txt(el, 24)).filter(Boolean))].slice(0, 3);
  const unavailable = opts.filter((o) => o.disabled || /sold|unavailable|disabled|line-through/i.test(o.className + ' ' + (o.labels && o.labels[0] ? o.labels[0].className : ''))).length;
  return { type: host.tagName.toLowerCase(), label: legend.join(' / ') || txt(host, 30), optionCount: opts.length, unavailableOptions: unavailable, anySelected: opts.some((o) => o.checked || o.selected), aboveFold: aboveFold(host), selector: sel(host), ...(hosts.indexOf(host) === 0 ? {} : {}) };
});
if (vhost) out.selectors.variantSelector = rec(vhost);
if (hosts[1]) out.selectors.variantSelector2 = rec(hosts[1]);
const seenCopy = new Set();
for (const el of qa('p, li, div, span, summary, details, a, small', info)) {
  if (!vis(el) || el.children.length > 4 || el.closest(cx('recommend,upsell,card'))) continue;
  const t = txt(el, 160);
  if (t.length < 8 || t.length > 160 || seenCopy.has(t) || scripty(t) || !/ship|deliver|return|exchange|free |guarantee|in stock|arrives|dispatch|klarna|afterpay|sezzle|affirm|installments|pick ?up in store/i.test(t)) continue;
  if ([...seenCopy].some((s) => s.includes(t))) continue;
  seenCopy.add(t);
  out.shippingReturnsCopy.push({ text: t, aboveFold: aboveFold(el), selector: sel(el) });
  if (!out.selectors.shippingBlock && /ship|deliver|return/i.test(t)) out.selectors.shippingBlock = rec(el);
  if (out.shippingReturnsCopy.length >= 6) break;
}
if (!out.shippingReturnsCopy.length) out.shippingReturnsCopy = 'absent';
for (const el of qa('shopify-payment-button, .shopify-payment-button, ' + cx('dynamic-checkout,paypal,shop-pay,apple-pay,google-pay') + ', iframe[title*="PayPal" i]', info)) if (vis(el)) out.expressPayOnPdp.push((txt(el, 30) || el.tagName.toLowerCase()).toLowerCase());
out.expressPayOnPdp = [...new Set(out.expressPayOnPdp)];
const hooks = { reviews: 'yotpo|jdgm|judgeme|okendo|stamped|loox|trustpilot|bazaarvoice|reviews\\.io|junip', bnpl: 'klarna|afterpay|sezzle|affirm|clearpay|zip-widget', sizing: 'kiwi|truefit|sizebay|fit-?finder|size-?guide|size-?chart', chat: 'gorgias|intercom|zendesk|tidio|drift|crisp', recommendations: 'rebuy|nosto|limespot|wiser|recom', bopis: 'pickup|store-availability|bopis' };
for (const [kind, re] of Object.entries(hooks)) {
  const rx = new RegExp(re, 'i');
  const hits = qa('[class], [id]').filter((el) => vis(el) && rx.test(el.className + ' ' + el.id)).slice(0, 3);
  if (hits.length) out.widgets.push(kind + ':' + [...new Set(hits.map((el) => (el.className + ' ' + el.id).match(rx)[0].toLowerCase()))].join('/') + (hits.some(aboveFold) ? ' (above fold)' : ''));
}
out.aboveFold = { foldPx: window.innerHeight, price: !!(priceEl && aboveFold(priceEl)), cta: !!(cta && aboveFold(cta)), variantSelector: !!(vhost && aboveFold(vhost)), shippingOrReturnsCopy: Array.isArray(out.shippingReturnsCopy) && out.shippingReturnsCopy.some((c) => c.aboveFold && /ship|deliver|return/i.test(c.text)), reviewsWidget: out.widgets.some((w) => /^reviews.*above fold/.test(w)), expressPay: out.expressPayOnPdp.length > 0 };
out.selectors.title = titleEl ? rec(titleEl) : null;
return emit(out);
} catch (e) { return JSON.stringify({ scriptError: String(e && e.message || e), stage: 'read_pdp' }); }
})()

